export type FgSamplers =
  | {
      category: "pianos";
      kind:
        | "default"
        | "brokenCassette"
        | "curlyElectric"
        | "dragonMagicOld"
        | "softSteinway";
      label:
        | "Default"
        | "Broken cassette"
        | "Curly electric"
        | "Dragon magic"
        | "Soft steinway";
      playOnlyDefined: boolean;
      definedNotes: string[];
    }
  | {
      category: "strings";
      kind: "brokenCello" | "uncleJohns5StringBanjo";
      label: "Broken cello" | "Uncle John's five string banjo";
      playOnlyDefined: boolean;
      definedNotes: string[];
    }
  | {
      category: "winds";
      kind:
        | "brassFrenchHorn"
        | "brassTrombone"
        | "brassTrumpet"
        | "brassTuba"
        | "classicSlideWhistle"
        | "forestFlute"
        | "oboe";
      label:
        | "Brass French horn"
        | "Brass trombone"
        | "Brass trumpet"
        | "Brass tuba"
        | "Classic slide whistle"
        | "Forest flute"
        | "Oboe";
      playOnlyDefined: boolean;
      definedNotes: string[];
    };

const fgSamplers = {
  pianos: {
    default: {
      sampler: {
        urls: {
          A0: "A0.mp3",
          C1: "C1.mp3",
          "D#1": "Ds1.mp3",
          "F#1": "Fs1.mp3",
          A1: "A1.mp3",
          C2: "C2.mp3",
          "D#2": "Ds2.mp3",
          "F#2": "Fs2.mp3",
          A2: "A2.mp3",
          C3: "C3.mp3",
          "D#3": "Ds3.mp3",
          "F#3": "Fs3.mp3",
          A3: "A3.mp3",
          C4: "C4.mp3",
          "D#4": "Ds4.mp3",
          "F#4": "Fs4.mp3",
          A4: "A4.mp3",
          C5: "C5.mp3",
          "D#5": "Ds5.mp3",
          "F#5": "Fs5.mp3",
          A5: "A5.mp3",
          C6: "C6.mp3",
          "D#6": "Ds6.mp3",
          "F#6": "Fs6.mp3",
          A6: "A6.mp3",
          C7: "C7.mp3",
          "D#7": "Ds7.mp3",
          "F#7": "Fs7.mp3",
          A7: "A7.mp3",
          C8: "C8.mp3",
        },
        release: 1,
        baseUrl: "https://tonejs.github.io/audio/salamander/",
      },
      label: "Default",
      playOnlyDefined: false,
    },
    acPiano1: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/pianos/acPiano1/",
      },
      label: "AC piano 1",
      playOnlyDefined: false,
    },
    acPiano2: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/pianos/acPiano2/",
      },
      label: "AC piano 2",
      playOnlyDefined: false,
    },
    bellPiano: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/pianos/bellPiano/",
      },
      label: "Bell piano",
      playOnlyDefined: false,
    },
    brokenCassette: {
      sampler: {
        urls: {
          A0: "A0.wav",
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
          "D#5": "D#5.wav",
          "F#5": "F#5.wav",
          A5: "A5.wav",
          C6: "C6.wav",
          "D#6": "D#6.wav",
          "F#6": "F#6.wav",
          A6: "A6.wav",
          "A#6": "A#6.wav",
          B6: "B6.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/pianos/brokenCassette/",
      },
      label: "Broken cassette",
      playOnlyDefined: false,
    },
    claviPiano: {
      sampler: {
        urls: {
          A0: "A0.wav",
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/pianos/claviPiano/",
      },
      label: "Clavi Piano",
      playOnlyDefined: false,
    },
    curlyElectric: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "F#1": "F#1.wav",
          C2: "C2.wav",
          "F#2": "F#2.wav",
          C3: "C3.wav",
          "F#3": "F#3.wav",
          C4: "C4.wav",
          "F#4": "F#4.wav",
          C5: "C5.wav",
          "F#5": "F#5.wav",
          B5: "B5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/pianos/curlyElectric/",
      },
      label: "Curly electric",
      playOnlyDefined: false,
    },
    dragonMagicOld: {
      sampler: {
        urls: {
          C1: "C1.wav",
          G1: "G1.wav",
          C2: "C2.wav",
          G2: "G2.wav",
          C3: "C3.wav",
          G3: "G3.wav",
          C4: "C4.wav",
          G4: "G4.wav",
          C5: "C5.wav",
          G5: "G5.wav",
          C6: "C6.wav",
          G6: "G6.wav",
          C7: "C7.wav",
          G7: "G7.wav",
          C8: "C8.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/pianos/dragonMagicOld/",
      },
      label: "Dragon magic",
      playOnlyDefined: false,
    },
    electricPiano1: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/pianos/electricPiano1/",
      },
      label: "Electric piano 1",
      playOnlyDefined: false,
    },
    electricPiano2: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/pianos/electricPiano2/",
      },
      label: "Electric piano 2",
      playOnlyDefined: false,
    },
    electricPiano3: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/pianos/electricPiano3/",
      },
      label: "Electric piano 3",
      playOnlyDefined: false,
    },
    electricPiano4: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/pianos/electricPiano4/",
      },
      label: "Electric piano 4",
      playOnlyDefined: false,
    },
    electricPiano5: {
      sampler: {
        urls: {
          A0: "A0.wav",
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "F#4": "F#4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/pianos/electricPiano5/",
      },
      label: "Electric piano 5",
      playOnlyDefined: false,
    },
    softSteinway: {
      sampler: {
        urls: {
          C0: "C0.wav",
          G0: "G0.wav",
          D1: "D1.wav",
          A1: "A1.wav",
          E2: "E2.wav",
          B2: "B2.wav",
          "F#3": "F#3.wav",
          "C#4": "C#4.wav",
          "G#4": "G#4.wav",
          "D#5": "D#5.wav",
          "A#5": "A#5.wav",
          F6: "F6.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/pianos/softSteinway/",
      },
      label: "Soft Steinway",
      playOnlyDefined: false,
    },
    toyPiano: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/pianos/toyPiano/",
      },
      label: "Toy piano",
      playOnlyDefined: false,
    },
  },
  strings: {
    acBass: {
      sampler: {
        urls: {
          A0: "A0.wav",
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/acBass/",
      },
      label: "AC bass",
      playOnlyDefined: false,
    },
    acGuitar: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/acGuitar/",
      },
      label: "AC guitar",
      playOnlyDefined: false,
    },
    acousticGuitar: {
      sampler: {
        urls: {
          E1: "E1.wav",
          "F#1": "F#1.wav",
          "G#1": "G#1.wav",
          "A#1": "A#1.wav",
          C2: "C2.wav",
          D2: "D2.wav",
          E2: "E2.wav",
          "F#2": "F#2.wav",
          "G#2": "G#2.wav",
          "A#2": "A#2.wav",
          C3: "C3.wav",
          D3: "D3.wav",
          E3: "E3.wav",
          "F#3": "F#3.wav",
          "G#3": "G#3.wav",
          "A#3": "A#3.wav",
          C4: "C4.wav",
          D4: "D4.wav",
          E4: "E4.wav",
          "F#4": "F#4.wav",
          "G#4": "G#4.wav",
          "A#4": "A#4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/acousticGuitar/",
      },
      label: "Acoustic guitar",
      playOnlyDefined: false,
    },
    anaBass: {
      sampler: {
        urls: {
          A0: "A0.wav",
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          A3: "A3.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/anaBass/",
      },
      label: "Ana bass",
      playOnlyDefined: false,
    },
    AXAFifthsBounceGuitar: {
      sampler: {
        urls: {
          B1: "B1.wav",
          C2: "C2.wav",
          "C#2": "C#2.wav",
          D2: "D2.wav",
          "D#2": "D#2.wav",
          E2: "E2.wav",
          F2: "F2.wav",
          "F#2": "F#2.wav",
          G2: "G2.wav",
          "G#2": "G#2.wav",
          A2: "A2.wav",
          "A#2": "A#2.wav",
          B2: "B2.wav",
          C3: "C3.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "D#3.wav",
          E3: "E3.wav",
          F3: "F3.wav",
          "F#3": "F#3.wav",
          G3: "G3.wav",
          "G#3": "G#3.wav",
          A3: "A3.wav",
          "A#3": "A#3.wav",
          B3: "B3.wav",
          C4: "C4.wav",
          "C#4": "C#4.wav",
          D4: "D4.wav",
          "D#4": "D#4.wav",
          E4: "E4.wav",
          F4: "F4.wav",
          "F#4": "F#4.wav",
          G4: "G4.wav",
          "G#4": "G#4.wav",
          A4: "A4.wav",
          "A#4": "A#4.wav",
          B4: "B4.wav",
          C5: "C5.wav",
          "C#5": "C#5.wav",
          D5: "D5.wav",
          "D#5": "D#5.wav",
          E5: "E5.wav",
          F5: "F5.wav",
          "F#5": "F#5.wav",
          G5: "G5.wav",
          "G#5": "G#5.wav",
          A5: "A5.wav",
          "A#5": "A#5.wav",
          B5: "B5.wav",
          C6: "C6.wav",
          "C#6": "C#6.wav",
          D6: "D6.wav",
          "D#6": "D#6.wav",
          E6: "E6.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/AXAFifthsBounceGuitar/",
      },
      label: "AXA fifths bounce guitar",
      playOnlyDefined: false,
    },
    AXAVoodooVibeGuitar: {
      sampler: {
        urls: {
          B1: "B1.wav",
          C2: "C2.wav",
          "C#2": "C#2.wav",
          D2: "D2.wav",
          "D#2": "D#2.wav",
          E2: "E2.wav",
          F2: "F2.wav",
          "F#2": "F#2.wav",
          G2: "G2.wav",
          "G#2": "G#2.wav",
          A2: "A2.wav",
          "A#2": "A#2.wav",
          B2: "B2.wav",
          C3: "C3.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "D#3.wav",
          E3: "E3.wav",
          F3: "F3.wav",
          "F#3": "F#3.wav",
          G3: "G3.wav",
          "G#3": "G#3.wav",
          A3: "A3.wav",
          "A#3": "A#3.wav",
          B3: "B3.wav",
          C4: "C4.wav",
          "C#4": "C#4.wav",
          D4: "D4.wav",
          "D#4": "D#4.wav",
          E4: "E4.wav",
          F4: "F4.wav",
          "F#4": "F#4.wav",
          G4: "G4.wav",
          "G#4": "G#4.wav",
          A4: "A4.wav",
          "A#4": "A#4.wav",
          B4: "B4.wav",
          C5: "C5.wav",
          "C#5": "C#5.wav",
          D5: "D5.wav",
          "D#5": "D#5.wav",
          E5: "E5.wav",
          F5: "F5.wav",
          "F#5": "F#5.wav",
          G5: "G5.wav",
          "G#5": "G#5.wav",
          A5: "A5.wav",
          "A#5": "A#5.wav",
          B5: "B5.wav",
          C6: "C6.wav",
          "C#6": "C#6.wav",
          D6: "D6.wav",
          "D#6": "D#6.wav",
          E6: "E6.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/AXAVoodooVibeGuitar/",
      },
      label: "AXA voodoo vibe guitar",
      playOnlyDefined: false,
    },
    beyondBowCello: {
      sampler: {
        urls: {
          C1: "C1.wav",
          D1: "D1.wav",
          G1: "G1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          D2: "D2.wav",
          G2: "G2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          D3: "D3.wav",
          G3: "G3.wav",
          C4: "C4.wav",
          D4: "D4.wav",
          G4: "G4.wav",
          A4: "A4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/beyondBowCello/",
      },
      label: "Beyond bow cello",
      playOnlyDefined: false,
    },
    brightGuitar: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/brightGuitar/",
      },
      label: "Bright guitar",
      playOnlyDefined: false,
    },
    brokenCello: {
      sampler: {
        urls: {
          "C#1": "C#1.wav",
          E1: "E1.wav",
          G1: "G1.wav",
          "A#1": "A#1.wav",
          "C#2": "C#2.wav",
          E2: "E2.wav",
          G2: "G2.wav",
          "A#2": "A#2.wav",
          E3: "E3.wav",
          G3: "G3.wav",
          "A#3": "A#3.wav",
          "C#3": "C#3.wav",
          "C#4": "C#4.wav",
          E4: "E4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/brokenCello/",
      },
      label: "Broken cello",
      playOnlyDefined: false,
    },
    cello: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/cello/",
      },
      label: "Cello",
      playOnlyDefined: false,
    },
    clankyAmpMetalGuitar: {
      sampler: {
        urls: {
          C0: "C0.wav",
          "C#0": "C#0.wav",
          D0: "D0.wav",
          "D#0": "D#0.wav",
          E0: "E0.wav",
          F0: "F0.wav",
          "F#0": "F#0.wav",
          G0: "G0.wav",
          "G#0": "G#0.wav",
          A0: "A0.wav",
          "A#0": "A#0.wav",
          B0: "B0.wav",
          C1: "C1.wav",
          "C#1": "C#1.wav",
          D1: "D1.wav",
          "D#1": "D#1.wav",
          E1: "E1.wav",
          F1: "F1.wav",
          "F#1": "F#1.wav",
          G1: "G1.wav",
          "G#1": "G#1.wav",
          A1: "A1.wav",
          "A#1": "A#1.wav",
          B1: "B1.wav",
          C2: "C2.wav",
          "C#2": "C#2.wav",
          D2: "D2.wav",
          "D#2": "D#2.wav",
          E2: "E2.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/clankyAmpMetalGuitar/",
      },
      label: "Clanky amp metal guitar",
      playOnlyDefined: false,
    },
    clankyMetalBassGuitar: {
      sampler: {
        urls: {
          C0: "C0.wav",
          "C#0": "C#0.wav",
          D0: "D0.wav",
          "D#0": "D#0.wav",
          E0: "E0.wav",
          F0: "F0.wav",
          "F#0": "F#0.wav",
          G0: "G0.wav",
          "G#0": "G#0.wav",
          A0: "A0.wav",
          "A#0": "A#0.wav",
          B0: "B0.wav",
          C1: "C1.wav",
          "C#1": "C#1.wav",
          D1: "D1.wav",
          "D#1": "D#1.wav",
          E1: "E1.wav",
          F1: "F1.wav",
          "F#1": "F#1.wav",
          G1: "G1.wav",
          "G#1": "G#1.wav",
          A1: "A1.wav",
          "A#1": "A#1.wav",
          B1: "B1.wav",
          C2: "C2.wav",
          "C#2": "C#2.wav",
          D2: "D2.wav",
          "D#2": "D#2.wav",
          E2: "E2.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/clankyMetalBassGuitar/",
      },
      label: "Clanky metal bass guitar",
      playOnlyDefined: false,
    },
    electricBass1: {
      sampler: {
        urls: {
          A0: "A0.wav",
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/electricBass1/",
      },
      label: "Electric bass 1",
      playOnlyDefined: false,
    },
    electricBass2: {
      sampler: {
        urls: {
          A0: "A0.wav",
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "F#3": "F#3.wav",
          C4: "C4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/electricBass2/",
      },
      label: "Electric bass 2",
      playOnlyDefined: false,
    },
    ferrumIronGuitar: {
      sampler: {
        urls: {
          C3: "C3.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "D#3.wav",
          E3: "E3.wav",
          F3: "F3.wav",
          "F#3": "F#3.wav",
          G3: "G3.wav",
          "G#3": "G#3.wav",
          A3: "A3.wav",
          "A#3": "A#3.wav",
          B3: "B3.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/ferrumIronGuitar/",
      },
      label: "Ferrum iron guitar",
      playOnlyDefined: false,
    },
    freshGuitar: {
      sampler: {
        urls: {
          C2: "C2.wav",
          E2: "E2.wav",
          C3: "C3.wav",
          E3: "E3.wav",
          "G#3": "G#3.wav",
          C4: "C4.wav",
          E4: "E4.wav",
          "G#4": "G#4.wav",
          E5: "E5.wav",
          "G#5": "G#5.wav",
          "G#6": "G#6.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/freshGuitar/",
      },
      label: "Fresh guitar",
      playOnlyDefined: false,
    },
    fretlessGuitar: {
      sampler: {
        urls: {
          A0: "A0.wav",
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          A4: "A4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/fretlessGuitar/",
      },
      label: "Fretless guitar",
      playOnlyDefined: false,
    },
    fuzzGuitar: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/fuzzGuitar/",
      },
      label: "Fuzz guitar",
      playOnlyDefined: false,
    },
    jarreBass: {
      sampler: {
        urls: {
          A0: "A0.wav",
          A1: "A1.wav",
          A2: "A2.wav",
          A3: "A3.wav",
          "D#1": "D#1.wav",
          "D#2": "D#2.wav",
          "D#3": "D#3.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/jarreBass/",
      },
      label: "Jarre bass",
      playOnlyDefined: false,
    },
    longFMBass: {
      sampler: {
        urls: {
          G0: "G0.wav",
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/longFMBass/",
      },
      label: "Long FM bass",
      playOnlyDefined: false,
    },
    MexicanGuitarron: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "C#1": "C#1.wav",
          D1: "D1.wav",
          "D#1": "D#1.wav",
          E1: "E1.wav",
          F1: "F1.wav",
          "F#1": "F#1.wav",
          G1: "G1.wav",
          "G#1": "G#1.wav",
          A1: "A1.wav",
          "A#1": "A#1.wav",
          B1: "B1.wav",
          C2: "C2.wav",
          "C#2": "C#2.wav",
          D2: "D2.wav",
          "D#2": "D#2.wav",
          E2: "E2.wav",
          F2: "F2.wav",
          "F#2": "F#2.wav",
          G2: "G2.wav",
          "G#2": "G#2.wav",
          A2: "A2.wav",
          "A#2": "A#2.wav",
          B2: "B2.wav",
          "B#2": "B#2.wav",
          C3: "C3.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "D#3.wav",
          E3: "E3.wav",
          F3: "F3.wav",
          "F#3": "F#3.wav",
          G3: "G3.wav",
          "G#3": "G#3.wav",
          A3: "A3.wav",
          "A#3": "A#3.wav",
          B3: "B3.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/MexicanGuitarron/",
      },
      label: "Mexican guitarron",
      playOnlyDefined: false,
    },
    moogBass: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "F#1": "F#1.wav",
          C2: "C2.wav",
          "F#2": "F#2.wav",
          C3: "C3.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/moogBass/",
      },
      label: "Moog bass",
      playOnlyDefined: false,
    },
    mutedGuitar: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          A4: "A4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/mutedGuitar/",
      },
      label: "Muted guitar",
      playOnlyDefined: false,
    },
    RJSGuitar: {
      sampler: {
        urls: {
          A2: "A2.wav",
          A3: "A3.wav",
          C3: "C3.wav",
          D3: "D3.wav",
          E2: "E2.wav",
          E3: "E3.wav",
          G2: "G2.wav",
          G3: "G3.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/RJSGuitar/",
      },
      label: "RJS guitar",
      playOnlyDefined: false,
    },
    shortFMBass: {
      sampler: {
        urls: {
          A0: "A0.wav",
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          A4: "A4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/shortFMBass/",
      },
      label: "Short FM bass",
      playOnlyDefined: false,
    },
    strings1: {
      sampler: {
        urls: {
          A0: "A0.wav",
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/strings1/",
      },
      label: "Strings 1",
      playOnlyDefined: false,
    },
    strings2: {
      sampler: {
        urls: {
          A0: "A0.wav",
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/strings2/",
      },
      label: "Strings 2",
      playOnlyDefined: false,
    },
    sweepBass: {
      sampler: {
        urls: {
          A0: "A0.wav",
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/sweepBass/",
      },
      label: "Sweep bass",
      playOnlyDefined: false,
    },
    synthBass: {
      sampler: {
        urls: {
          A0: "A0.wav",
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/synthBass/",
      },
      label: "Synth bass",
      playOnlyDefined: false,
    },
    uncleJohns5StringBanjo: {
      sampler: {
        urls: {
          C3: "C3.wav",
          D3: "D3.wav",
          G3: "G3.wav",
          B3: "B3.wav",
          D4: "D4.wav",
          G4: "G4.wav",
          D5: "D5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/uncleJohns5StringBanjo/",
      },
      label: "Uncle John's five string banjo",
      playOnlyDefined: false,
    },
    violin: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/strings/violin/",
      },
      label: "Violin",
      playOnlyDefined: false,
    },
  },
  winds: {
    bassFrenchHorn: {
      sampler: {
        urls: {
          "A#1": "A#1.wav",
          B1: "B1.wav",
          C2: "C2.wav",
          "C#2": "C#2.wav",
          D2: "D2.wav",
          "D#2": "D#2.wav",
          E2: "E2.wav",
          F2: "F2.wav",
          "F#2": "F#2.wav",
          G2: "G2.wav",
          "G#2": "G#2.wav",
          A2: "A2.wav",
          "A#2": "A#2.wav",
          B2: "B2.wav",
          C3: "C3.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "D#3.wav",
          E3: "E3.wav",
          F3: "F3.wav",
          "F#3": "F#3.wav",
          G3: "G3.wav",
          "G#3": "G#3.wav",
          A3: "A3.wav",
          "A#3": "A#3.wav",
          B3: "B3.wav",
          C4: "C4.wav",
          "C#4": "C#4.wav",
          D4: "D4.wav",
          "D#4": "D#4.wav",
          E4: "E4.wav",
          F4: "F4.wav",
          "F#4": "F#4.wav",
          G4: "G4.wav",
          "G#4": "G#4.wav",
          A4: "A4.wav",
          "A#4": "A#4.wav",
          B4: "B4.wav",
          C5: "C5.wav",
          "C#5": "C#5.wav",
          D5: "D5.wav",
          "D#5": "D#5.wav",
          E5: "E5.wav",
          F5: "F5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/winds/brassFrenchHorn/",
      },
      label: "Bass French horn",
      playOnlyDefined: false,
    },
    bassTrombone: {
      sampler: {
        urls: {
          A1: "A1.wav",
          "A#1": "A#1.wav",
          B1: "B1.wav",
          F1: "F1.wav",
          "F#1": "F#1.wav",
          G1: "G1.wav",
          "G#1": "G#1.wav",
          C2: "C2.wav",
          "C#2": "C#2.wav",
          D2: "D2.wav",
          "D#2": "D#2.wav",
          E2: "E2.wav",
          F2: "F2.wav",
          "F#2": "F#2.wav",
          G2: "G2.wav",
          "G#2": "G#2.wav",
          A2: "A2.wav",
          "A#2": "A#2.wav",
          B2: "B2.wav",
          C3: "C3.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "D#3.wav",
          E3: "E3.wav",
          F3: "F3.wav",
          "F#3": "F#3.wav",
          G3: "G3.wav",
          "G#3": "G#3.wav",
          A3: "A3.wav",
          "A#3": "A#3.wav",
          B3: "B3.wav",
          C4: "C4.wav",
          "C#4": "C#4.wav",
          D4: "D4.wav",
          "D#4": "D#4.wav",
          E4: "E4.wav",
          F4: "F4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/winds/brassTrombone/",
      },
      label: "Bass trombone",
      playOnlyDefined: false,
    },
    bassTrumpet: {
      sampler: {
        urls: {
          A3: "A3.wav",
          "A#3": "A#3.wav",
          B3: "B3.wav",
          F3: "F3.wav",
          "F#3": "F#3.wav",
          G3: "G3.wav",
          "G#3": "G#3.wav",
          C4: "C4.wav",
          "C#4": "C#4.wav",
          D4: "D4.wav",
          "D#4": "D#4.wav",
          E4: "E4.wav",
          F4: "F4.wav",
          "F#4": "F#4.wav",
          G4: "G4.wav",
          "G#4": "G#4.wav",
          A4: "A4.wav",
          "A#4": "A#4.wav",
          B4: "B4.wav",
          C5: "C5.wav",
          "C#5": "C#5.wav",
          D5: "D5.wav",
          "D#5": "D#5.wav",
          E5: "E5.wav",
          F5: "F5.wav",
          "F#5": "F#5.wav",
          G5: "G5.wav",
          "G#5": "G#5.wav",
          A5: "A5.wav",
          "A#5": "A#5.wav",
          B5: "B5.wav",
          C6: "C6.wav",
          "C#6": "C#6.wav",
          D6: "D6.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/winds/brassTrumpet/",
      },
      label: "Bass trumpet",
      playOnlyDefined: false,
    },
    bassTuba: {
      sampler: {
        urls: {
          D1: "D1.wav",
          "D#1": "D#1.wav",
          E1: "E1.wav",
          "F#1": "F#1.wav",
          B1: "B1.wav",
          C2: "C2.wav",
          "C#2": "C#2.wav",
          D2: "D2.wav",
          "D#2": "D#2.wav",
          E2: "E2.wav",
          F2: "F2.wav",
          "G#2": "G#2.wav",
          A2: "A2.wav",
          "A#2": "A#2.wav",
          B2: "B2.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "D#3.wav",
          E3: "E3.wav",
          F3: "F3.wav",
          "F#3": "F#3.wav",
          "G#3": "G#3.wav",
          A3: "A3.wav",
          "A#3": "A#3.wav",
          B3: "B3.wav",
          C4: "C4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/winds/brassTuba/",
      },
      label: "Bass tuba",
      playOnlyDefined: false,
    },
    clarinet: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/winds/clarinet/",
      },
      label: "Clarinet",
      playOnlyDefined: false,
    },
    classicSlideWhistle: {
      sampler: {
        urls: {
          G3: "G3.wav",
          A3: "A3.wav",
          B3: "B3.wav",
          C4: "C4.wav",
          D4: "D4.wav",
          E4: "E4.wav",
          G4: "G4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
          F5: "F5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/winds/classicSlideWhistle/",
      },
      label: "Classic slide whistle",
      playOnlyDefined: false,
    },
    flugelhorn: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/winds/flugelhorn/",
      },
      label: "Flugelhorn",
      playOnlyDefined: false,
    },
    flute: {
      sampler: {
        urls: {
          C2: "C2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/winds/flute/",
      },
      label: "Flute",
      playOnlyDefined: false,
    },
    forestFlute: {
      sampler: {
        urls: {
          E4: "E4.wav",
          "F#4": "F#4.wav",
          "G#4": "G#4.wav",
          "A#4": "A#4.wav",
          B4: "B4.wav",
          D5: "D5.wav",
          D6: "D6.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/winds/forestFlute/",
      },
      label: "Forest flute",
      playOnlyDefined: false,
    },
    hoverFlute: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "C#1": "C#1.wav",
          D1: "D1.wav",
          "D#1": "D#1.wav",
          E1: "E1.wav",
          F1: "F1.wav",
          "F#1": "F#1.wav",
          G1: "G1.wav",
          "G#1": "G#1.wav",
          A1: "A1.wav",
          "A#1": "A#1.wav",
          B1: "B1.wav",
          C2: "C2.wav",
          "C#2": "C#2.wav",
          D2: "D2.wav",
          "D#2": "D#2.wav",
          E2: "E2.wav",
          F2: "F2.wav",
          "F#2": "F#2.wav",
          G2: "G2.wav",
          "G#2": "G#2.wav",
          A2: "A2.wav",
          "A#2": "A#2.wav",
          B2: "B2.wav",
          C3: "C3.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "D#3.wav",
          E3: "E3.wav",
          F3: "F3.wav",
          "F#3": "F#3.wav",
          G3: "G3.wav",
          "G#3": "G#3.wav",
          A3: "A3.wav",
          "A#3": "A#3.wav",
          B3: "B3.wav",
          C4: "C4.wav",
          "C#4": "C#4.wav",
          D4: "D4.wav",
          "D#4": "D#4.wav",
          E4: "E4.wav",
          F4: "F4.wav",
          "F#4": "F#4.wav",
          G4: "G4.wav",
          "G#4": "G#4.wav",
          A4: "A4.wav",
          "A#4": "A#4.wav",
          B4: "B4.wav",
          C5: "C5.wav",
          "C#5": "C#5.wav",
          D5: "D5.wav",
          "D#5": "D#5.wav",
          E5: "E5.wav",
          F5: "F5.wav",
          "F#5": "F#5.wav",
          G5: "G5.wav",
          "G#5": "G#5.wav",
          A5: "A5.wav",
          "A#5": "A#5.wav",
          B5: "B5.wav",
          C6: "C6.wav",
          "C#6": "C#6.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/winds/hoverFlute/",
      },
      label: "Hover flute",
      playOnlyDefined: true,
    },
    oboe1: {
      sampler: {
        urls: {
          C4: "C4.wav",
          "C#4": "C#4.wav",
          D4: "D4.wav",
          "D#4": "D#4.wav",
          E4: "E4.wav",
          F4: "F4.wav",
          "F#4": "F#4.wav",
          G4: "G4.wav",
          "G#4": "G#4.wav",
          A4: "A4.wav",
          "A#4": "A#4.wav",
          B4: "B4.wav",
          C5: "C5.wav",
          "C#5": "C#5.wav",
          D5: "D5.wav",
          "D#5": "D#5.wav",
          E5: "E5.wav",
          F5: "F5.wav",
          "F#5": "F#5.wav",
          G5: "G5.wav",
          "G#5": "G#5.wav",
          A5: "A5.wav",
          "A#5": "A#5.wav",
          B5: "B5.wav",
          C6: "C6.wav",
          "C#6": "C#6.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/winds/oboe1/",
      },
      label: "Oboe 1",
      playOnlyDefined: false,
    },
    oboe2: {
      sampler: {
        urls: {
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/winds/oboe2/",
      },
      label: "Oboe 2",
      playOnlyDefined: false,
    },
    recorder: {
      sampler: {
        urls: {
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/winds/recorder/",
      },
      label: "Recorder",
      playOnlyDefined: false,
    },
    saxophone: {
      sampler: {
        urls: {
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/winds/saxophone/",
      },
      label: "Saxophone",
      playOnlyDefined: false,
    },
    tenorSaxophone: {
      sampler: {
        urls: {
          A3: "A3.wav",
          "A#3": "A#3.wav",
          C4: "C4.wav",
          D4: "D4.wav",
          "D#4": "D#4.wav",
          F4: "F4.wav",
          G4: "G4.wav",
          A4: "A4.wav",
          "A#4": "A#4.wav",
          C5: "C5.wav",
          D5: "D5.wav",
          "D#5": "D#5.wav",
          F5: "F5.wav",
          G5: "G5.wav",
          A5: "A5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/winds/tenorSaxophone/",
      },
      label: "Tenor saxophone",
      playOnlyDefined: false,
    },
    whistle: {
      sampler: {
        urls: {
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/winds/whistle/",
      },
      label: "Whistle",
      playOnlyDefined: false,
    },
  },
  drums: {
    brokenSplashCymbalGong: {
      sampler: {
        urls: {
          "C#3": "C#3.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          D3: "D3.wav",
          E3: "E3.wav",
          "F#3": "F#3.wav",
          F3: "F3.wav",
          G3: "G3.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/drums/brokenSplashCymbalGong/",
      },
      label: "Broken splash cymbal gong",
      playOnlyDefined: true,
    },
    claveFrog: {
      sampler: {
        urls: {
          C0: "C0.wav",
          "C#0": "C#0.wav",
          D0: "D0.wav",
          "D#0": "D#0.wav",
          E0: "E0.wav",
          F0: "F0.wav",
          "F#0": "F#0.wav",
          G0: "G0.wav",
          "G#0": "G#0.wav",
          A0: "A0.wav",
          "A#0": "A#0.wav",
          B0: "B0.wav",
          C1: "C1.wav",
          "C#1": "C#1.wav",
          D1: "D1.wav",
          "D#1": "D#1.wav",
          E1: "E1.wav",
          F1: "F1.wav",
          "F#1": "F#1.wav",
          G1: "G1.wav",
          "G#1": "G#1.wav",
          A1: "A1.wav",
          "A#1": "A#1.wav",
          B1: "B1.wav",
          C2: "C2.wav",
          "C#2": "C#2.wav",
          D2: "D2.wav",
          "D#2": "D#2.wav",
          E2: "E2.wav",
          F2: "F2.wav",
          "F#2": "F#2.wav",
          G2: "G2.wav",
          "G#2": "G#2.wav",
          A2: "A2.wav",
          "A#2": "A#2.wav",
          B2: "B2.wav",
          C3: "C3.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "D#3.wav",
          E3: "E3.wav",
          F3: "F3.wav",
          "F#3": "F#3.wav",
          G3: "G3.wav",
          "G#3": "G#3.wav",
          A3: "A3.wav",
          "A#3": "A#3.wav",
          B3: "B3.wav",
          C4: "C4.wav",
          "C#4": "C#4.wav",
          D4: "D4.wav",
          "D#4": "D#4.wav",
          E4: "E4.wav",
          F4: "F4.wav",
          "F#4": "F#4.wav",
          G4: "G4.wav",
          "G#4": "G#4.wav",
          A4: "A4.wav",
          "A#4": "A#4.wav",
          B4: "B4.wav",
          C5: "C5.wav",
          "C#5": "C#5.wav",
          D5: "D5.wav",
          "D#5": "D#5.wav",
          E5: "E5.wav",
          F5: "F5.wav",
          "F#5": "F#5.wav",
          G5: "G5.wav",
          "G#5": "G#5.wav",
          A5: "A5.wav",
          "A#5": "A#5.wav",
          B5: "B5.wav",
          C6: "C6.wav",
          "C#6": "C#6.wav",
          D6: "D6.wav",
          "D#6": "D#6.wav",
          E6: "E6.wav",
          F6: "F6.wav",
          "F#6": "F#6.wav",
          G6: "G6.wav",
          "G#6": "G#6.wav",
          A6: "A6.wav",
          "A#6": "A#6.wav",
          B6: "B6.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/drums/claveFrog/",
      },
      label: "Clave frog",
      playOnlyDefined: true,
    },
    garageSaleDrumKit: {
      sampler: {
        urls: {
          C0: "C0.wav",
          "C#0": "C#0.wav",
          D0: "D0.wav",
          "D#0": "D#0.wav",
          E0: "E0.wav",
          F0: "F0.wav",
          "F#0": "F#0.wav",
          G0: "G0.wav",
          "G#0": "G#0.wav",
          A0: "A0.wav",
          "A#0": "A#0.wav",
          B0: "B0.wav",
          C1: "C1.wav",
          "C#1": "C#1.wav",
          D1: "D1.wav",
          "D#1": "D#1.wav",
          E1: "E1.wav",
          F1: "F1.wav",
          "F#1": "F#1.wav",
          G1: "G1.wav",
          "G#1": "G#1.wav",
          A1: "A1.wav",
          "A#1": "A#1.wav",
          B1: "B1.wav",
          C2: "C2.wav",
          "C#2": "C#2.wav",
          D2: "D2.wav",
          "D#2": "D#2.wav",
          E2: "E2.wav",
          F2: "F2.wav",
          "F#2": "F#2.wav",
          G2: "G2.wav",
          "G#2": "G#2.wav",
          A2: "A2.wav",
          "A#2": "A#2.wav",
          B2: "B2.wav",
          C3: "C3.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "D#3.wav",
          E3: "E3.wav",
          F3: "F3.wav",
          "F#3": "F#3.wav",
          G3: "G3.wav",
          "G#3": "G#3.wav",
          A3: "A3.wav",
          "A#3": "A#3.wav",
          B3: "B3.wav",
          C4: "C4.wav",
          "C#4": "C#4.wav",
          D4: "D4.wav",
          "D#4": "D#4.wav",
          E4: "E4.wav",
          F4: "F4.wav",
          "F#4": "F#4.wav",
          G4: "G4.wav",
          "G#4": "G#4.wav",
          A4: "A4.wav",
          "A#4": "A#4.wav",
          B4: "B4.wav",
          C5: "C5.wav",
          "C#5": "C#5.wav",
          D5: "D5.wav",
          "D#5": "D#5.wav",
          E5: "E5.wav",
          F5: "F5.wav",
          "F#5": "F#5.wav",
          G5: "G5.wav",
          "G#5": "G#5.wav",
          A5: "A5.wav",
          "A#5": "A#5.wav",
          B5: "B5.wav",
          C6: "C6.wav",
          "C#6": "C#6.wav",
          D6: "D6.wav",
          "D#6": "D#6.wav",
          E6: "E6.wav",
          F6: "F6.wav",
          "F#6": "F#6.wav",
          G6: "G6.wav",
          "G#6": "G#6.wav",
          A6: "A6.wav",
          "A#6": "A#6.wav",
          B6: "B6.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/drums/garageSaleDrumKit/",
      },
      label: "Garage sale drum kit",
      playOnlyDefined: true,
    },
    handBells: {
      sampler: {
        urls: {
          C1: "C1.wav",
          D1: "D1.wav",
          E1: "E1.wav",
          F1: "F1.wav",
          "F#1": "F#1.wav",
          G1: "G1.wav",
          "G#1": "G#1.wav",
          A1: "A1.wav",
          B1: "B1.wav",
          C2: "C2.wav",
          D2: "D2.wav",
          E2: "E2.wav",
          F2: "F2.wav",
          "F#2": "F#2.wav",
          G2: "G2.wav",
          A2: "A2.wav",
          B2: "B2.wav",
          C3: "C3.wav",
          D3: "D3.wav",
          E3: "E3.wav",
          F3: "F3.wav",
          "F#3": "F#3.wav",
          G3: "G3.wav",
          "G#3": "G#3.wav",
          A3: "A3.wav",
          B3: "B3.wav",
          C4: "C4.wav",
          D4: "D4.wav",
          E4: "E4.wav",
          F4: "F4.wav",
          "F#4": "F#4.wav",
          G4: "G4.wav",
          A4: "A4.wav",
          B4: "B4.wav",
          C5: "C5.wav",
          D5: "D5.wav",
          E5: "E5.wav",
          F5: "F5.wav",
          "F#5": "F#5.wav",
          G5: "G5.wav",
          "G#5": "G#5.wav",
          A5: "A5.wav",
          B5: "B5.wav",
          C6: "C6.wav",
          D6: "D6.wav",
          E6: "E6.wav",
          F6: "F6.wav",
          "F#6": "F#6.wav",
          G6: "G6.wav",
          A6: "A6.wav",
          B6: "B6.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/drums/handBells/",
      },
      label: "Hand bells",
      playOnlyDefined: true,
    },
    JonsCajons: {
      sampler: {
        urls: {
          C2: "C2.wav",
          "C#2": "C#2.wav",
          D2: "D2.wav",
          "D#2": "D#2.wav",
          E2: "E2.wav",
          F2: "F2.wav",
          "F#2": "F#2.wav",
          G2: "G2.wav",
          "G#2": "G#2.wav",
          A2: "A2.wav",
          "A#2": "A#2.wav",
          B2: "B2.wav",
          C3: "C3.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "D#3.wav",
          G3: "G3.wav",
          "G#3": "G#3.wav",
          A3: "A3.wav",
          "A#3": "A#3.wav",
          B3: "B3.wav",
          C4: "C4.wav",
          "C#4": "C#4.wav",
          D4: "D4.wav",
          "D#4": "D#4.wav",
          E4: "E4.wav",
          F4: "F4.wav",
          "F#4": "F#4.wav",
          G4: "G4.wav",
          "G#4": "G#4.wav",
          A4: "A4.wav",
          "A#4": "A#4.wav",
          B4: "B4.wav",
          C5: "C5.wav",
          "C#5": "C#5.wav",
          D5: "D5.wav",
          "D#5": "D#5.wav",
          E5: "E5.wav",
          F5: "F5.wav",
          "F#5": "F#5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/drums/JonsCajons/",
      },
      label: "Jon's cajons",
      playOnlyDefined: true,
    },
    kitchenDrumKit: {
      sampler: {
        urls: {
          C2: "C2.wav",
          "C#2": "C#2.wav",
          D2: "D2.wav",
          "D#2": "D#2.wav",
          E2: "E2.wav",
          "F#2": "F#2.wav",
          "G#2": "G#2.wav",
          C3: "C3.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "D#3.wav",
          E3: "E3.wav",
          "F#3": "F#3.wav",
          "G#3": "G#3.wav",
          C4: "C4.wav",
          "C#4": "C#4.wav",
          D4: "D4.wav",
          "D#4": "D#4.wav",
          E4: "E4.wav",
          F4: "F4.wav",
          "F#4": "F#4.wav",
          G4: "G4.wav",
          "G#4": "G#4.wav",
          C5: "C5.wav",
          "C#5": "C#5.wav",
          D5: "D5.wav",
          "D#5": "D#5.wav",
          E5: "E5.wav",
          F5: "F5.wav",
          "F#5": "F#5.wav",
          G5: "G5.wav",
          "G#5": "G#5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/drums/kitchenDrumKit/",
      },
      label: "Kitchen drum kit",
      playOnlyDefined: true,
    },
    metallophon: {
      sampler: {
        urls: {
          C3: "C3.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "D#3.wav",
          E3: "E3.wav",
          F3: "F3.wav",
          "F#3": "F#3.wav",
          G3: "G3.wav",
          "G#3": "G#3.wav",
          A3: "A3.wav",
          "A#3": "A#3.wav",
          B3: "B3.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/drums/metallophon/",
      },
      label: "Metallophon",
      playOnlyDefined: true,
    },
    slitLogDrum: {
      sampler: {
        urls: {
          "C#3": "C#3.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          D3: "D3.wav",
          E3: "E3.wav",
          F3: "F3.wav",
          "F#3": "F#3.wav",
          G3: "G3.wav",
          "G#3": "G#3.wav",
          A3: "A3.wav",
          "A#3": "A#3.wav",
          B3: "B3.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/drums/slitLogDrum/",
      },
      label: "Slit log drum",
      playOnlyDefined: true,
    },
    solarWinds: {
      sampler: {
        urls: {
          C3: "C3.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "D#3.wav",
          E3: "E3.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/drums/solarWinds/",
      },
      label: "Solar winds",
      playOnlyDefined: true,
    },
    tinCanDrums: {
      sampler: {
        urls: {
          C0: "C0.wav",
          "C#0": "C#0.wav",
          D0: "D0.wav",
          "D#0": "D#0.wav",
          E0: "E0.wav",
          F0: "F0.wav",
          "F#0": "F#0.wav",
          G0: "G0.wav",
          "G#0": "G#0.wav",
          A0: "A0.wav",
          "A#0": "A#0.wav",
          B0: "B0.wav",
          C1: "C1.wav",
          "C#1": "C#1.wav",
          D1: "D1.wav",
          "D#1": "D#1.wav",
          E1: "E1.wav",
          F1: "F1.wav",
          "F#1": "F#1.wav",
          G1: "G1.wav",
          "G#1": "G#1.wav",
          A1: "A1.wav",
          "A#1": "A#1.wav",
          B1: "B1.wav",
          C2: "C2.wav",
          "C#2": "C#2.wav",
          D2: "D2.wav",
          "D#2": "D#2.wav",
          E2: "E2.wav",
          F2: "F2.wav",
          "F#2": "F#2.wav",
          G2: "G2.wav",
          "G#2": "G#2.wav",
          A2: "A2.wav",
          "A#2": "A#2.wav",
          B2: "B2.wav",
          C3: "C3.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "D#3.wav",
          E3: "E3.wav",
          F3: "F3.wav",
          "F#3": "F#3.wav",
          G3: "G3.wav",
          "G#3": "G#3.wav",
          A3: "A3.wav",
          "A#3": "A#3.wav",
          B3: "B3.wav",
          C4: "C4.wav",
          "C#4": "C#4.wav",
          D4: "D4.wav",
          "D#4": "D#4.wav",
          E4: "E4.wav",
          F4: "F4.wav",
          "F#4": "F#4.wav",
          G4: "G4.wav",
          "G#4": "G#4.wav",
          A4: "A4.wav",
          "A#4": "A#4.wav",
          B4: "B4.wav",
          C5: "C5.wav",
          "C#5": "C#5.wav",
          D5: "D5.wav",
          "D#5": "D#5.wav",
          E5: "E5.wav",
          F5: "F5.wav",
          "F#5": "F#5.wav",
          G5: "G5.wav",
          "G#5": "G#5.wav",
          A5: "A5.wav",
          "A#5": "A#5.wav",
          B5: "B5.wav",
          C6: "C6.wav",
          "C#6": "C#6.wav",
          D6: "D6.wav",
          "D#6": "D#6.wav",
          E6: "E6.wav",
          F6: "F6.wav",
          "F#6": "F#6.wav",
          G6: "G6.wav",
          "G#6": "G#6.wav",
          A6: "A6.wav",
          "A#6": "A#6.wav",
          B6: "B6.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/drums/tinCanDrums/",
      },
      label: "Tin can drums",
      playOnlyDefined: true,
    },
  },
  synths: {
    leadSynth1: {
      sampler: {
        urls: {
          "D#1": "D#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/synths/leadSynth1/",
      },
      label: "Lead synth 1",
      playOnlyDefined: true,
    },
    leadSynth2: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#2.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/synths/leadSynth2/",
      },
      label: "Lead synth 2",
      playOnlyDefined: true,
    },
    leadSynth3: {
      sampler: {
        urls: {
          A1: "A1.wav",
          "D#2": "D#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/synths/leadSynth3/",
      },
      label: "Lead synth 3",
      playOnlyDefined: true,
    },
    leadSynth4: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/synths/leadSynth4/",
      },
      label: "Lead synth 4",
      playOnlyDefined: true,
    },
    leadSynth5: {
      sampler: {
        urls: {
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/synths/leadSynth5/",
      },
      label: "Lead synth 5",
      playOnlyDefined: true,
    },
    leadSynth6: {
      sampler: {
        urls: {
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/synths/leadSynth6/",
      },
      label: "Lead synth 6",
      playOnlyDefined: true,
    },
    leadSynth7: {
      sampler: {
        urls: {
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/synths/leadSynth7/",
      },
      label: "Lead synth 7",
      playOnlyDefined: true,
    },
    padSynth1: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/synths/padSynth1/",
      },
      label: "Pad synth 1",
      playOnlyDefined: true,
    },
    padSynth2: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/synths/padSynth2/",
      },
      label: "Pad synth 2",
      playOnlyDefined: true,
    },
  },
  organs: {
    bottleOrgan: {
      sampler: {
        urls: {
          "C#2": "C#2.wav",
          "C#3": "C#3.wav",
          C2: "C2.wav",
          C3: "C3.wav",
          "D#2": "D#2.wav",
          "D#3": "D#3.wav",
          D2: "D2.wav",
          D3: "D3.wav",
          E3: "E3.wav",
          "F#3": "F#3.wav",
          F3: "F3.wav",
          G3: "G3.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/organs/bottleOrgan/",
      },
      label: "Bottle organ",
      playOnlyDefined: true,
    },
    cassetteTapeOrgan: {
      sampler: {
        urls: {
          C3: "C3.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "#3.wav",
          E3: "E3.wav",
          F3: "F3.wav",
          "F#3": "F#3.wav",
          G3: "G3.wav",
          "G#3": "G#3.wav",
          "A#3": "A#3.wav",
          A3: "A3.wav",
          B3: "B3.wav",
          C4: "C4.wav",
          "C#4": "C#4.wav",
          D4: "D4.wav",
          "D#4": "#4.wav",
          E4: "E4.wav",
          F4: "F4.wav",
          "F#4": "F#4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/organs/cassetteTapeOrgan/",
      },
      label: "Cassette tape organ",
      playOnlyDefined: false,
    },
    electricOrgan1: {
      sampler: {
        urls: {
          A0: "A0.wav",
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/organs/electricOrgan1/",
      },
      label: "Electric organ 1",
      playOnlyDefined: false,
    },
    electricOrgan2: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/organs/electricOrgan2/",
      },
      label: "Electric organ 2",
      playOnlyDefined: false,
    },
    electricOrgan3: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/organs/electricOrgan3/",
      },
      label: "Electric organ 3",
      playOnlyDefined: false,
    },
    littleRedOrgan: {
      sampler: {
        urls: {
          "C#2": "C#2.wav",
          "D#2": "D#2.wav",
          F2: "F2.wav",
          G2: "G2.wav",
          A2: "A2.wav",
          B2: "B2.wav",
          "C#3": "C#3.wav",
          "D#3": "D#3.wav",
          F3: "F3.wav",
          G3: "G3.wav",
          A3: "A3.wav",
          B3: "B3.wav",
          "C#4": "C#4.wav",
          "D#4": "D#4.wav",
          F4: "F4.wav",
          G4: "G4.wav",
          A4: "A4.wav",
          B4: "B4.wav",
          "C#5": "C#5.wav",
          "D#5": "D#5.wav",
          F5: "F5.wav",
          G5: "G5.wav",
          A5: "A5.wav",
          B5: "B5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/organs/littleRedOrgan/",
      },
      label: "Little red organ",
      playOnlyDefined: false,
    },
    pipeOrgan1: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          F3: "F3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/organs/pipeOrgan1/",
      },
      label: "Pipe organ 1",
      playOnlyDefined: false,
    },
    pipeOrgan2: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/organs/pipeOrgan2/",
      },
      label: "Pipe organ 2",
      playOnlyDefined: false,
    },
    pipeOrgan3: {
      sampler: {
        urls: {
          A0: "A0.wav",
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/organs/pipeOrgan3/",
      },
      label: "Pipe organ 3",
      playOnlyDefined: false,
    },
    spookyOrgan: {
      sampler: {
        urls: {
          A3: "A3.wav",
          B4: "B4.wav",
          "C#6": "C#6.wav",
          C2: "C2.wav",
          D3: "D3.wav",
          E4: "E4.wav",
          "F#5": "F#5.wav",
          G2: "G2.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/organs/spookyOrgan/",
      },
      label: "Spooky organ",
      playOnlyDefined: false,
    },
  },
  misc: {
    accordion: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/misc/accordion/",
      },
      label: "Accordion",
      playOnlyDefined: false,
    },
    ancientBronzeBells: {
      sampler: {
        urls: {
          C3: "C3.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "D#3.wav",
          E3: "E3.wav",
          F3: "F3.wav",
          "F#3": "F#3.wav",
          G3: "G3.wav",
          "G#3": "G#3.wav",
          A3: "A3.wav",
          "A#3": "A#3.wav",
          B3: "B3.wav",
          "C#4": "C#4.wav",
          C4: "C4.wav",
          D4: "D4.wav",
          "D#4": "D#4.wav",
          E4: "E4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/misc/ancientBronzeBells/",
      },
      label: "Ancient bronze bells",
      playOnlyDefined: true,
    },
    bells1: {
      sampler: {
        urls: {
          C1: "C1.wav",
          G1: "G1.wav",
          C2: "C2.wav",
          G2: "G2.wav",
          C3: "C3.wav",
          G3: "G3.wav",
          C4: "C4.wav",
          G4: "G4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/misc/bells1/",
      },
      label: "Bells 1",
      playOnlyDefined: false,
    },
    bells2: {
      sampler: {
        urls: {
          C1: "C1.wav",
          E1: "E1.wav",
          C2: "C2.wav",
          E2: "E2.wav",
          C3: "C3.wav",
          E3: "E3.wav",
          C4: "C4.wav",
          E4: "E4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/misc/bells2/",
      },
      label: "Bells 2",
      playOnlyDefined: false,
    },
    clavichord: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/misc/clavichord/",
      },
      label: "Clavichord",
      playOnlyDefined: false,
    },
    cosmos: {
      sampler: {
        urls: {
          C3: "C3.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "D#3.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/misc/cosmos/",
      },
      label: "Cosmos",
      playOnlyDefined: true,
    },
    gong: {
      sampler: {
        urls: {
          C3: "C3.wav",
          "C#3": "C#3.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/misc/gong/",
      },
      label: "Gong",
      playOnlyDefined: true,
    },
    harmonica: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/misc/harmonica/",
      },
      label: "Harmonica",
      playOnlyDefined: false,
    },
    marimba: {
      sampler: {
        urls: {
          A0: "A0.wav",
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/misc/marimba/",
      },
      label: "Marimba",
      playOnlyDefined: false,
    },
    mechanisedChoir: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "C#1": "C#1.wav",
          D1: "D1.wav",
          "D#1": "D#1.wav",
          E1: "E1.wav",
          F1: "F1.wav",
          "F#1": "F#1.wav",
          G1: "G1.wav",
          "G#1": "G#1.wav",
          A1: "A1.wav",
          "A#1": "A#1.wav",
          B1: "B1.wav",
          C2: "C2.wav",
          "C#2": "C#2.wav",
          D2: "D2.wav",
          "D#2": "D#2.wav",
          E2: "E2.wav",
          F2: "F2.wav",
          "F#2": "F#2.wav",
          G2: "G2.wav",
          "G#2": "G#2.wav",
          A2: "A2.wav",
          "A#2": "A#2.wav",
          B2: "B2.wav",
          C3: "C3.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "D#3.wav",
          E3: "E3.wav",
          F3: "F3.wav",
          "F#3": "F#3.wav",
          G3: "G3.wav",
          "G#3": "G#3.wav",
          A3: "A3.wav",
          "A#3": "A#3.wav",
          B3: "B3.wav",
          C4: "C4.wav",
          "C#4": "C#4.wav",
          D4: "D4.wav",
          "D#4": "D#4.wav",
          E4: "E4.wav",
          F4: "F4.wav",
          "F#4": "F#4.wav",
          G4: "G4.wav",
          "G#4": "G#4.wav",
          A4: "A4.wav",
          "A#4": "A#4.wav",
          B4: "B4.wav",
          C5: "C5.wav",
          "C#5": "C#5.wav",
          D5: "D5.wav",
          "D#5": "D#5.wav",
          E5: "E5.wav",
          F5: "F5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/misc/mechanisedChoir/",
      },
      label: "Mechanised choir",
      playOnlyDefined: false,
    },
    MicahsChoir: {
      sampler: {
        urls: {
          G3: "G3.wav",
          "G#3": "G#3.wav",
          A3: "A3.wav",
          "A#3": "A#3.wav",
          B3: "B3.wav",
          C4: "C4.wav",
          "C#4": "C#4.wav",
          D4: "D4.wav",
          "D#4": "D#4.wav",
          E4: "E4.wav",
          F4: "F4.wav",
          "F#4": "F#4.wav",
          G4: "G4.wav",
          "G#4": "G#4.wav",
          A4: "A4.wav",
          "A#4": "A#4.wav",
          B4: "B4.wav",
          C5: "C5.wav",
          "C#5": "C#5.wav",
          D5: "D5.wav",
          "D#5": "D#5.wav",
          E5: "E5.wav",
          F5: "F5.wav",
          "F#5": "F#5.wav",
          G5: "G5.wav",
          "G#5": "G#5.wav",
          A5: "A5.wav",
          "A#5": "A#5.wav",
          B5: "B5.wav",
          C6: "C6.wav",
          "C#6": "C#6.wav",
          D6: "D6.wav",
          "D#6": "D#6.wav",
          E6: "E6.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/misc/MicahsChoir/",
      },
      label: "Micah's choir",
      playOnlyDefined: false,
    },
    orchestra: {
      sampler: {
        urls: {
          A0: "A0.wav",
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/misc/orchestra/",
      },
      label: "Orchestra",
      playOnlyDefined: false,
    },
    plasmaDriveKalimba: {
      sampler: {
        urls: {
          A3: "A3.wav",
          A4: "A4.wav",
          B3: "B3.wav",
          B4: "B4.wav",
          C3: "C3.wav",
          C4: "C4.wav",
          D3: "D3.wav",
          D4: "D4.wav",
          E3: "E3.wav",
          E4: "E4.wav",
          F3: "F3.wav",
          F4: "F4.wav",
          G3: "G3.wav",
          G4: "G4.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/misc/plasmaDriveKalimba/",
      },
      label: "Plasma drive kalimba",
      playOnlyDefined: false,
    },
    spellSinger: {
      sampler: {
        urls: {
          C2: "C2.wav",
          "C#2": "C#2.wav",
          D2: "D2.wav",
          "D#2": "D#2.wav",
          E2: "E2.wav",
          F2: "F2.wav",
          "F#2": "F#2.wav",
          G2: "G2.wav",
          "G#2": "G#2.wav",
          A2: "A2.wav",
          "A#2": "A#2.wav",
          B2: "B2.wav",
          C3: "C3.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "D#3.wav",
          E3: "E3.wav",
          F3: "F3.wav",
          "F#3": "F#3.wav",
          G3: "G3.wav",
          "G#3": "G#3.wav",
          A3: "A3.wav",
          "A#3": "A#3.wav",
          B3: "B3.wav",
          C4: "C4.wav",
          "C#4": "C#4.wav",
          D4: "D4.wav",
          "D#4": "D#4.wav",
          E4: "E4.wav",
          F4: "F4.wav",
          "F#4": "F#4.wav",
          G4: "G4.wav",
          "G#4": "G#4.wav",
          A4: "A4.wav",
          "A#4": "A#4.wav",
          B4: "B4.wav",
          C5: "C5.wav",
          "C#5": "C#5.wav",
          D5: "D5.wav",
          "D#5": "D#5.wav",
          E5: "E5.wav",
          F5: "F5.wav",
          "F#5": "F#5.wav",
          G5: "G5.wav",
          "G#5": "G#5.wav",
          A5: "A5.wav",
          "A#5": "A#5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/misc/spellSinger/",
      },
      label: "Spell singer",
      playOnlyDefined: false,
    },
    streetBountyXylophone: {
      sampler: {
        urls: {
          C0: "C0.wav",
          "C#0": "C#0.wav",
          D0: "D0.wav",
          "D#0": "D#0.wav",
          E0: "E0.wav",
          F0: "F0.wav",
          "F#0": "F#0.wav",
          G0: "G0.wav",
          "G#0": "G#0.wav",
          A0: "A0.wav",
          "A#0": "A#0.wav",
          B0: "B0.wav",
          C1: "C1.wav",
          "C#1": "C#1.wav",
          D1: "D1.wav",
          "D#1": "D#1.wav",
          E1: "E1.wav",
          F1: "F1.wav",
          "F#1": "F#1.wav",
          G1: "G1.wav",
          "G#1": "G#1.wav",
          A1: "A1.wav",
          "A#1": "A#1.wav",
          B1: "B1.wav",
          C2: "C2.wav",
          "C#2": "C#2.wav",
          D2: "D2.wav",
          "D#2": "D#2.wav",
          E2: "E2.wav",
          F2: "F2.wav",
          "F#2": "F#2.wav",
          G2: "G2.wav",
          "G#2": "G#2.wav",
          A2: "A2.wav",
          "A#2": "A#2.wav",
          B2: "B2.wav",
          C3: "C3.wav",
          "C#3": "C#3.wav",
          D3: "D3.wav",
          "D#3": "D#3.wav",
          E3: "E3.wav",
          F3: "F3.wav",
          "F#3": "F#3.wav",
          G3: "G3.wav",
          "G#3": "G#3.wav",
          A3: "A3.wav",
          "A#3": "A#3.wav",
          B3: "B3.wav",
          C4: "C4.wav",
          "C#4": "C#4.wav",
          D4: "D4.wav",
          "D#4": "D#4.wav",
          E4: "E4.wav",
          F4: "F4.wav",
          "F#4": "F#4.wav",
          G4: "G4.wav",
          "G#4": "G#4.wav",
          A4: "A4.wav",
          "A#4": "A#4.wav",
          B4: "B4.wav",
          C5: "C5.wav",
          "C#5": "C#5.wav",
          D5: "D5.wav",
          "D#5": "D#5.wav",
          E5: "E5.wav",
          F5: "F5.wav",
          "F#5": "F#5.wav",
          G5: "G5.wav",
          "G#5": "G#5.wav",
          A5: "A5.wav",
          "A#5": "A#5.wav",
          B5: "B5.wav",
          C6: "C6.wav",
          "C#6": "C#6.wav",
          D6: "D6.wav",
          "D#6": "D#6.wav",
          E6: "E6.wav",
          F6: "F6.wav",
          "F#6": "F#6.wav",
          G6: "G6.wav",
          "G#6": "G#6.wav",
          A6: "A6.wav",
          "A#6": "A#6.wav",
          B6: "B6.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/misc/streetBountyXylophone/",
      },
      label: "Street bounty xylophone",
      playOnlyDefined: false,
    },
    vibraphone: {
      sampler: {
        urls: {
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/misc/vibraphone/",
      },
      label: "Vibraphone",
      playOnlyDefined: false,
    },
    xylophone: {
      sampler: {
        urls: {
          C1: "C1.wav",
          "D#1": "D#1.wav",
          "F#1": "F#1.wav",
          A1: "A1.wav",
          C2: "C2.wav",
          "D#2": "D#2.wav",
          "F#2": "F#2.wav",
          A2: "A2.wav",
          C3: "C3.wav",
          "D#3": "D#3.wav",
          "F#3": "F#3.wav",
          A3: "A3.wav",
          C4: "C4.wav",
          "D#4": "D#4.wav",
          "F#4": "F#4.wav",
          A4: "A4.wav",
          C5: "C5.wav",
        },
        release: 1,
        baseUrl: "/audioSamples/misc/xylophone/",
      },
      label: "Xylophone",
      playOnlyDefined: false,
    },
  },
};

export default fgSamplers;
