export type AudioEffectTypes =
  | "robot"
  | "echo"
  | "alien"
  | "underwater"
  | "telephone"
  | "space"
  | "distortion"
  | "vintage"
  | "psychedelic"
  | "deepBass"
  | "highEnergy"
  | "ambient"
  | "glitch"
  | "muffled"
  | "crystal"
  | "heavyMetal"
  | "dreamy"
  | "horror"
  | "sciFi"
  | "dystopian"
  | "retroGame"
  | "ghostly"
  | "metallic"
  | "hypnotic"
  | "cyberpunk"
  | "windy"
  | "radio"
  | "explosion"
  | "whisper"
  | "submarine"
  | "windTunnel"
  | "crushedBass"
  | "ethereal"
  | "electroSting"
  | "heartbeat"
  | "underworld"
  | "sizzling"
  | "staticNoise"
  | "bubbly"
  | "thunder"
  | "echosOfThePast";

export const audioEffectStylesEncodingMap = {
  robot: 0,
  echo: 1,
  alien: 2,
  underwater: 3,
  telephone: 4,
  space: 5,
  distortion: 6,
  vintage: 7,
  psychedelic: 8,
  deepBass: 9,
  highEnergy: 10,
  ambient: 11,
  glitch: 12,
  muffled: 13,
  crystal: 14,
  heavyMetal: 15,
  dreamy: 16,
  horror: 17,
  sciFi: 18,
  dystopian: 19,
  retroGame: 20,
  ghostly: 21,
  metallic: 22,
  hypnotic: 23,
  cyberpunk: 24,
  windy: 24,
  radio: 25,
  explosion: 26,
  whisper: 27,
  submarine: 28,
  windTunnel: 29,
  crushedBass: 30,
  ethereal: 31,
  electroSting: 32,
  heartbeat: 33,
  underworld: 34,
  sizzling: 35,
  staticNoise: 36,
  bubbly: 37,
  thunder: 38,
  echosOfThePast: 39,
};
