import { MeshesData, MeshJSON } from "./typeContant";
import { HideBackgroundEffectTypes } from "../context/currentEffectsStylesContext/typeConstant";

export const baseMaskData: {
  "2Durl": string;
  "3Durl": string;
  size: number;
  data: MeshJSON | undefined;
} = {
  "2Durl": "/2DAssets/masks/baseMask/baseMask_512x512.png",
  "3Durl": "/3DAssets/masks/baseMask/baseMask.json",
  size: 512,
  data: undefined,
};

const assetMeshes: MeshesData = {
  mustaches: {
    disguiseMustache: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "disguiseMustache_2D",
        meshPath: "/2DAssets/mustaches/disguiseMustache/",
        meshFile: "disguiseMustache_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "disguiseMustache_gltf",
        meshPath: "/3DAssets/mustaches/disguiseMustache/",
        meshFile: "disguiseMustache.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    fullMustache: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "fullMustache_2D",
        meshPath: "/2DAssets/mustaches/fullMustache/",
        meshFile: "fullMustache_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "fullMustache_gltf",
        meshPath: "/3DAssets/mustaches/fullMustache/",
        meshFile: "fullMustache.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    mustache1: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "mustache1_2D",
        meshPath: "/2DAssets/mustaches/mustache1/",
        meshFile: "mustache1_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "mustache1_gltf",
        meshPath: "/3DAssets/mustaches/mustache1/",
        meshFile: "mustache1.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    mustache2: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "mustache2_2D",
        meshPath: "/2DAssets/mustaches/mustache2/",
        meshFile: "mustache2_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "mustache2_gltf",
        meshPath: "/3DAssets/mustaches/mustache2/",
        meshFile: "mustache2.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    mustache3: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "mustache3_2D",
        meshPath: "/2DAssets/mustaches/mustache3/",
        meshFile: "mustache3_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "mustache3_gltf",
        meshPath: "/3DAssets/mustaches/mustache3/",
        meshFile: "mustache3.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    mustache4: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "mustache4_2D",
        meshPath: "/2DAssets/mustaches/mustache4/",
        meshFile: "mustache4_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "mustache4_gltf",
        meshPath: "/3DAssets/mustaches/mustache4/",
        meshFile: "mustache4.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    nicodemusMustache: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "nicodemusMustache_2D",
        meshPath: "/2DAssets/mustaches/nicodemusMustache/",
        meshFile: "nicodemusMustache_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "nicodemusMustache_gltf",
        meshPath: "/3DAssets/mustaches/nicodemusMustache/",
        meshFile: "nicodemusMustache.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    pencilMustache: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "pencilMustache_2D",
        meshPath: "/2DAssets/mustaches/pencilMustache/",
        meshFile: "pencilMustache_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "pencilMustache_gltf",
        meshPath: "/3DAssets/mustaches/pencilMustache/",
        meshFile: "pencilMustache.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    spongebobMustache: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "spongebobMustache_2D",
        meshPath: "/2DAssets/mustaches/spongebobMustache/",
        meshFile: "spongebobMustache_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "spongebobMustache_gltf",
        meshPath: "/3DAssets/mustaches/spongebobMustache/",
        meshFile: "spongebobMustache.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    tinyMustache: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "tinyMustache_2D",
        meshPath: "/2DAssets/mustaches/tinyMustache/",
        meshFile: "tinyMustache_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "tinyMustache_gltf",
        meshPath: "/3DAssets/mustaches/tinyMustache/",
        meshFile: "tinyMustache.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    wingedMustache: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "wingedMustache_2D",
        meshPath: "/2DAssets/mustaches/wingedMustache/",
        meshFile: "wingedMustache_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "wingedMustache_gltf",
        meshPath: "/3DAssets/mustaches/wingedMustache/",
        meshFile: "wingedMustache.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
  },
  beards: {
    chinBeard: {
      defaultMeshPlacement: "chin",
      planeMesh: {
        meshLabel: "chinBeard_2D",
        meshPath: "/2DAssets/beards/chinBeard/",
        meshFile: "chinBeard_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "chinBeard_gltf",
        meshPath: "/3DAssets/beards/chinBeard/",
        meshFile: "chinBeard.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    classicalCurlyBeard: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "classicalCurlyBeard_2D",
        meshPath: "/2DAssets/beards/classicalCurlyBeard/",
        meshFile: "classicalCurlyBeard_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "classicalCurlyBeard_gltf",
        meshPath: "/3DAssets/beards/classicalCurlyBeard/",
        meshFile: "classicalCurlyBeard.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    fullBeard: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "fullBeard_2D",
        meshPath: "/2DAssets/beards/fullBeard/",
        meshFile: "fullBeard_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "fullBeard_gltf",
        meshPath: "/3DAssets/beards/fullBeard/",
        meshFile: "fullBeard.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
  },
  masks: {
    alienMask: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "alienMask_2D",
        meshPath: "/2DAssets/masks/alienMask/",
        meshFile: "alienMask_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "alienMask_gltf",
        meshPath: "/3DAssets/masks/alienMask/",
        meshFile: "alienMask.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    baseMask: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "baseMask_2D",
        meshPath: "/2DAssets/masks/baseMask/",
        meshFile: "baseMask_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "baseMask_gltf",
        meshPath: "/3DAssets/masks/baseMask/",
        meshFile: "baseMask.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    clownMask: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "clownMask_2D",
        meshPath: "/2DAssets/masks/clownMask/",
        meshFile: "clownMask_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "clownMask_gltf",
        meshPath: "/3DAssets/masks/clownMask/",
        meshFile: "clownMask.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    creatureMask: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "creatureMask_2D",
        meshPath: "/2DAssets/masks/creatureMask/",
        meshFile: "creatureMask_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "creatureMask_gltf",
        meshPath: "/3DAssets/masks/creatureMask/",
        meshFile: "creatureMask.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    cyberMask: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "cyberMask_2D",
        meshPath: "/2DAssets/masks/cyberMask/",
        meshFile: "cyberMask_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "cyberMask_gltf",
        meshPath: "/3DAssets/masks/cyberMask/",
        meshFile: "cyberMask.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    darkKnightMask: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "darkKnightMask_2D",
        meshPath: "/2DAssets/masks/darkKnightMask/",
        meshFile: "darkKnightMask_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "darkKnightMask_gltf",
        meshPath: "/3DAssets/masks/darkKnightMask/",
        meshFile: "darkKnightMask.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    demonMask: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "demonMask_2D",
        meshPath: "/2DAssets/masks/demonMask/",
        meshFile: "demonMask_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "demonMask_gltf",
        meshPath: "/3DAssets/masks/demonMask/",
        meshFile: "demonMask.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    gasMask1: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "gasMask1_2D",
        meshPath: "/2DAssets/masks/gasMask1/",
        meshFile: "gasMask1_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "gasMask1_gltf",
        meshPath: "/3DAssets/masks/gasMask1/",
        meshFile: "gasMask1.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    gasMask2: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "gasMask2_2D",
        meshPath: "/2DAssets/masks/gasMask2/",
        meshFile: "gasMask2_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "gasMask2_gltf",
        meshPath: "/3DAssets/masks/gasMask2/",
        meshFile: "gasMask2.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    gasMask3: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "gasMask3_2D",
        meshPath: "/2DAssets/masks/gasMask3/",
        meshFile: "gasMask3_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "gasMask3_gltf",
        meshPath: "/3DAssets/masks/gasMask3/",
        meshFile: "gasMask3.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    gasMask4: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "gasMask4_2D",
        meshPath: "/2DAssets/masks/gasMask4/",
        meshFile: "gasMask4_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "gasMask4_gltf",
        meshPath: "/3DAssets/masks/gasMask4/",
        meshFile: "gasMask4.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    masqueradeMask: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "masqueradeMask_2D",
        meshPath: "/2DAssets/masks/masqueradeMask/",
        meshFile: "masqueradeMask_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "masqueradeMask_gltf",
        meshPath: "/3DAssets/masks/masqueradeMask/",
        meshFile: "masqueradeMask.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    metalManMask: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "metalManMask_2D",
        meshPath: "/2DAssets/masks/metalManMask/",
        meshFile: "metalManMask_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "metalManMask_gltf",
        meshPath: "/3DAssets/masks/metalManMask/",
        meshFile: "metalManMask.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    oniMask: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "oniMask_2D",
        meshPath: "/2DAssets/masks/oniMask/",
        meshFile: "oniMask_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "oniMask_gltf",
        meshPath: "/3DAssets/masks/oniMask/",
        meshFile: "oniMask.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    plagueDoctorMask: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "plagueDoctorMask_2D",
        meshPath: "/2DAssets/masks/plagueDoctorMask/",
        meshFile: "plagueDoctorMask_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "plagueDoctorMask_gltf",
        meshPath: "/3DAssets/masks/plagueDoctorMask/",
        meshFile: "plagueDoctorMask.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    sixEyesMask: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "sixEyesMask_2D",
        meshPath: "/2DAssets/masks/sixEyesMask/",
        meshFile: "sixEyesMask_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "sixEyesMask_gltf",
        meshPath: "/3DAssets/masks/sixEyesMask/",
        meshFile: "sixEyesMask.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    tenguMask: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "tenguMask_2D",
        meshPath: "/2DAssets/masks/tenguMask/",
        meshFile: "tenguMask_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "tenguMask_gltf",
        meshPath: "/3DAssets/masks/tenguMask/",
        meshFile: "tenguMask.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    threeFaceMask: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "threeFaceMask_2D",
        meshPath: "/2DAssets/masks/threeFaceMask/",
        meshFile: "threeFaceMask_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "threeFaceMask_gltf",
        meshPath: "/3DAssets/masks/threeFaceMask/",
        meshFile: "threeFaceMask.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    weldingMask: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "weldingMask_2D",
        meshPath: "/2DAssets/masks/weldingMask/",
        meshFile: "weldingMask_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "weldingMask_gltf",
        meshPath: "/3DAssets/masks/weldingMask/",
        meshFile: "weldingMask.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    woodlandMask: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "woodlandMask_2D",
        meshPath: "/2DAssets/masks/woodlandMask/",
        meshFile: "woodlandMask_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "woodlandMask_gltf",
        meshPath: "/3DAssets/masks/woodlandMask/",
        meshFile: "woodlandMask.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    woodPaintedMask: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "woodPaintedMask_2D",
        meshPath: "/2DAssets/masks/woodPaintedMask/",
        meshFile: "woodPaintedMask_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "woodPaintedMask_gltf",
        meshPath: "/3DAssets/masks/woodPaintedMask/",
        meshFile: "woodPaintedMask.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    zombieMask: {
      defaultMeshPlacement: "nose",
      planeMesh: {
        meshLabel: "zombieMask_2D",
        meshPath: "/2DAssets/masks/zombieMask/",
        meshFile: "zombieMask_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "zombieMask_gltf",
        meshPath: "/3DAssets/masks/zombieMask/",
        meshFile: "zombieMask.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
  },
  glasses: {
    defaultGlasses: {
      defaultMeshPlacement: "eyesCenter",
      planeMesh: {
        meshLabel: "defaultGlasses_2D",
        meshPath: "/2DAssets/glasses/defaultGlasses/",
        meshFile: "defaultGlasses_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "defaultGlasses_gltf",
        meshPath: "/3DAssets/glasses/defaultGlasses/",
        meshFile: "defaultGlasses.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    AmericaGlasses: {
      defaultMeshPlacement: "eyesCenter",
      planeMesh: {
        meshLabel: "AmericaGlasses_2D",
        meshPath: "/2DAssets/glasses/AmericaGlasses/",
        meshFile: "AmericaGlasses_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "AmericaGlasses_gltf",
        meshPath: "/3DAssets/glasses/AmericaGlasses/",
        meshFile: "AmericaGlasses.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    aviatorGoggles: {
      defaultMeshPlacement: "eyesCenter",
      planeMesh: {
        meshLabel: "aviatorGoggles_2D",
        meshPath: "/2DAssets/glasses/aviatorGoggles/",
        meshFile: "aviatorGoggles_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "aviatorGoggles_gltf",
        meshPath: "/3DAssets/glasses/aviatorGoggles/",
        meshFile: "aviatorGoggles.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    bloodyGlasses: {
      defaultMeshPlacement: "eyesCenter",
      planeMesh: {
        meshLabel: "bloodyGlasses_2D",
        meshPath: "/2DAssets/glasses/bloodyGlasses/",
        meshFile: "bloodyGlasses_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "bloodyGlasses_gltf",
        meshPath: "/3DAssets/glasses/bloodyGlasses/",
        meshFile: "bloodyGlasses.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    eyeProtectionGlasses: {
      defaultMeshPlacement: "eyesCenter",
      planeMesh: {
        meshLabel: "eyeProtectionGlasses_2D",
        meshPath: "/2DAssets/glasses/eyeProtectionGlasses/",
        meshFile: "eyeProtectionGlasses_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "eyeProtectionGlasses_gltf",
        meshPath: "/3DAssets/glasses/eyeProtectionGlasses/",
        meshFile: "eyeProtectionGlasses.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    glasses1: {
      defaultMeshPlacement: "eyesCenter",
      planeMesh: {
        meshLabel: "glasses1_2D",
        meshPath: "/2DAssets/glasses/glasses1/",
        meshFile: "glasses1_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "glasses1_gltf",
        meshPath: "/3DAssets/glasses/glasses1/",
        meshFile: "glasses1.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    glasses2: {
      defaultMeshPlacement: "eyesCenter",
      planeMesh: {
        meshLabel: "glasses2_2D",
        meshPath: "/2DAssets/glasses/glasses2/",
        meshFile: "glasses2_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "glasses2_gltf",
        meshPath: "/3DAssets/glasses/glasses2/",
        meshFile: "glasses2.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    glasses3: {
      defaultMeshPlacement: "eyesCenter",
      planeMesh: {
        meshLabel: "glasses3_2D",
        meshPath: "/2DAssets/glasses/glasses3/",
        meshFile: "glasses3_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "glasses3_gltf",
        meshPath: "/3DAssets/glasses/glasses3/",
        meshFile: "glasses3.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    glasses4: {
      defaultMeshPlacement: "eyesCenter",
      planeMesh: {
        meshLabel: "glasses4_2D",
        meshPath: "/2DAssets/glasses/glasses4/",
        meshFile: "glasses4_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "glasses4_gltf",
        meshPath: "/3DAssets/glasses/glasses4/",
        meshFile: "glasses4.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    glasses5: {
      defaultMeshPlacement: "eyesCenter",
      planeMesh: {
        meshLabel: "glasses5_2D",
        meshPath: "/2DAssets/glasses/glasses5/",
        meshFile: "glasses5_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "glasses5_gltf",
        meshPath: "/3DAssets/glasses/glasses5/",
        meshFile: "glasses5.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    glasses6: {
      defaultMeshPlacement: "eyesCenter",
      planeMesh: {
        meshLabel: "glasses6_2D",
        meshPath: "/2DAssets/glasses/glasses6/",
        meshFile: "glasses6_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "glasses6_gltf",
        meshPath: "/3DAssets/glasses/glasses6/",
        meshFile: "glasses6.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    memeGlasses: {
      defaultMeshPlacement: "eyesCenter",
      planeMesh: {
        meshLabel: "memeGlasses_2D",
        meshPath: "/2DAssets/glasses/memeGlasses/",
        meshFile: "memeGlasses_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "memeGlasses_gltf",
        meshPath: "/3DAssets/glasses/memeGlasses/",
        meshFile: "memeGlasses.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    militaryTacticalGlasses: {
      defaultMeshPlacement: "eyesCenter",
      planeMesh: {
        meshLabel: "militaryTacticalGlasses_2D",
        meshPath: "/2DAssets/glasses/militaryTacticalGlasses/",
        meshFile: "militaryTacticalGlasses_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "militaryTacticalGlasses_gltf",
        meshPath: "/3DAssets/glasses/militaryTacticalGlasses/",
        meshFile: "militaryTacticalGlasses.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    steampunkGlasses: {
      defaultMeshPlacement: "eyesCenter",
      planeMesh: {
        meshLabel: "steampunkGlasses_2D",
        meshPath: "/2DAssets/glasses/steampunkGlasses/",
        meshFile: "steampunkGlasses_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "steampunkGlasses_gltf",
        meshPath: "/3DAssets/glasses/steampunkGlasses/",
        meshFile: "steampunkGlasses.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    threeDGlasses: {
      defaultMeshPlacement: "eyesCenter",
      planeMesh: {
        meshLabel: "threeDGlasses_2D",
        meshPath: "/2DAssets/glasses/threeDGlasses/",
        meshFile: "threeDGlasses_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "threeDGlasses_gltf",
        meshPath: "/3DAssets/glasses/threeDGlasses/",
        meshFile: "threeDGlasses.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    toyGlasses: {
      defaultMeshPlacement: "eyesCenter",
      planeMesh: {
        meshLabel: "toyGlasses_2D",
        meshPath: "/2DAssets/glasses/toyGlasses/",
        meshFile: "toyGlasses_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "toyGlasses_gltf",
        meshPath: "/3DAssets/glasses/toyGlasses/",
        meshFile: "toyGlasses.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    shades: {
      defaultMeshPlacement: "eyesCenter",
      planeMesh: {
        meshLabel: "shades_2D",
        meshPath: "/2DAssets/glasses/shades/",
        meshFile: "shades_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "shades_gltf",
        meshPath: "/3DAssets/glasses/shades/",
        meshFile: "shades.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    VRGlasses: {
      defaultMeshPlacement: "eyesCenter",
      planeMesh: {
        meshLabel: "VRGlasses_2D",
        meshPath: "/2DAssets/glasses/VRGlasses/",
        meshFile: "VRGlasses_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "VRGlasses_gltf",
        meshPath: "/3DAssets/glasses/VRGlasses/",
        meshFile: "VRGlasses.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
  },
  hats: {
    AsianConicalHat: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "AsianConicalHat_2D",
        meshPath: "/2DAssets/hats/AsianConicalHat/",
        meshFile: "AsianConicalHat_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "AsianConicalHat_gltf",
        meshPath: "/3DAssets/hats/AsianConicalHat/",
        meshFile: "AsianConicalHat.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    aviatorHelmet: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "aviatorHelmet_2D",
        meshPath: "/2DAssets/hats/aviatorHelmet/",
        meshFile: "aviatorHelmet_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "aviatorHelmet_gltf",
        meshPath: "/3DAssets/hats/aviatorHelmet/",
        meshFile: "aviatorHelmet.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    bicornHat: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "bicornHat_2D",
        meshPath: "/2DAssets/hats/bicornHat/",
        meshFile: "bicornHat_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "bicornHat_gltf",
        meshPath: "/3DAssets/hats/bicornHat/",
        meshFile: "bicornHat.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    bicycleHelmet: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "bicycleHelmet_2D",
        meshPath: "/2DAssets/hats/bicycleHelmet/",
        meshFile: "bicycleHelmet_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "bicycleHelmet_gltf",
        meshPath: "/3DAssets/hats/bicycleHelmet/",
        meshFile: "bicycleHelmet.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    captainsHat: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "captainsHat_2D",
        meshPath: "/2DAssets/hats/captainsHat/",
        meshFile: "captainsHat_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "captainsHat_gltf",
        meshPath: "/3DAssets/hats/captainsHat/",
        meshFile: "captainsHat.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    chefHat: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "chefHat_2D",
        meshPath: "/2DAssets/hats/chefHat/",
        meshFile: "chefHat_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "chefHat_gltf",
        meshPath: "/3DAssets/hats/chefHat/",
        meshFile: "chefHat.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    chickenHat: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "chickenHat_2D",
        meshPath: "/2DAssets/hats/chickenHat/",
        meshFile: "chickenHat_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "chickenHat_gltf",
        meshPath: "/3DAssets/hats/chickenHat/",
        meshFile: "chickenHat.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    deadManHat: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "deadManHat_2D",
        meshPath: "/2DAssets/hats/deadManHat/",
        meshFile: "deadManHat_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "deadManHat_gltf",
        meshPath: "/3DAssets/hats/deadManHat/",
        meshFile: "deadManHat.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    dogEars: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "dogEars_2D",
        meshPath: "/2DAssets/hats/dogEars/",
        meshFile: "dogEars_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "dogEars_gltf",
        meshPath: "/3DAssets/hats/dogEars/",
        meshFile: "dogEars.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    flatCap: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "flatCap_2D",
        meshPath: "/2DAssets/hats/flatCap/",
        meshFile: "flatCap_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "flatCap_gltf",
        meshPath: "/3DAssets/hats/flatCap/",
        meshFile: "flatCap.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    hardHat: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "hardHat_2D",
        meshPath: "/2DAssets/hats/hardHat/",
        meshFile: "hardHat_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "hardHat_gltf",
        meshPath: "/3DAssets/hats/hardHat/",
        meshFile: "hardHat.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    hopliteHelmet: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "hopliteHelmet_2D",
        meshPath: "/2DAssets/hats/hopliteHelmet/",
        meshFile: "hopliteHelmet_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "hopliteHelmet_gltf",
        meshPath: "/3DAssets/hats/hopliteHelmet/",
        meshFile: "hopliteHelmet.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    militaryHat: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "militaryHat_2D",
        meshPath: "/2DAssets/hats/militaryHat/",
        meshFile: "militaryHat_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "militaryHat_gltf",
        meshPath: "/3DAssets/hats/militaryHat/",
        meshFile: "militaryHat.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    rabbitEars: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "rabbitEars_2D",
        meshPath: "/2DAssets/hats/rabbitEars/",
        meshFile: "rabbitEars_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "rabbitEars_gltf",
        meshPath: "/3DAssets/hats/rabbitEars/",
        meshFile: "rabbitEars.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    roundEarsHat: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "roundEarsHat_2D",
        meshPath: "/2DAssets/hats/roundEarsHat/",
        meshFile: "roundEarsHat_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "roundEarsHat_gltf",
        meshPath: "/3DAssets/hats/roundEarsHat/",
        meshFile: "roundEarsHat.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    santaHat: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "santaHat_2D",
        meshPath: "/2DAssets/hats/santaHat/",
        meshFile: "santaHat_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "santaHat_gltf",
        meshPath: "/3DAssets/hats/santaHat/",
        meshFile: "santaHat.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    seamanHat: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "seamanHat_2D",
        meshPath: "/2DAssets/hats/seamanHat/",
        meshFile: "seamanHat_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "seamanHat_gltf",
        meshPath: "/3DAssets/hats/seamanHat/",
        meshFile: "seamanHat.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    stylishHat: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "stylishHat_2D",
        meshPath: "/2DAssets/hats/stylishHat/",
        meshFile: "stylishHat_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "stylishHat_gltf",
        meshPath: "/3DAssets/hats/stylishHat/",
        meshFile: "stylishHat.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    superMarioOdysseyHat: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "superMarioOdysseyHat_2D",
        meshPath: "/2DAssets/hats/superMarioOdysseyHat/",
        meshFile: "superMarioOdysseyHat_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "superMarioOdysseyHat_gltf",
        meshPath: "/3DAssets/hats/superMarioOdysseyHat/",
        meshFile: "superMarioOdysseyHat.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    ushankaHat: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "ushankaHat_2D",
        meshPath: "/2DAssets/hats/ushankaHat/",
        meshFile: "ushankaHat_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "ushankaHat_gltf",
        meshPath: "/3DAssets/hats/ushankaHat/",
        meshFile: "ushankaHat.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    vikingHelmet: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "vikingHelmet_2D",
        meshPath: "/2DAssets/hats/vikingHelmet/",
        meshFile: "vikingHelmet_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "vikingHelmet_gltf",
        meshPath: "/3DAssets/hats/vikingHelmet/",
        meshFile: "vikingHelmet.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
  },
  pets: {
    angryHamster: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "angryHamster_2D",
        meshPath: "/2DAssets/pets/angryHamster/",
        meshFile: "angryHamster_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "angryHamster_gltf",
        meshPath: "/3DAssets/pets/angryHamster/",
        meshFile: "angryHamster.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    axolotl: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "axolotl_2D",
        meshPath: "/2DAssets/pets/axolotl/",
        meshFile: "axolotl_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "axolotl_gltf",
        meshPath: "/3DAssets/pets/axolotl/",
        meshFile: "axolotl.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    babyDragon: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "babyDragon_2D",
        meshPath: "/2DAssets/pets/babyDragon/",
        meshFile: "babyDragon_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "babyDragon_gltf",
        meshPath: "/3DAssets/pets/babyDragon/",
        meshFile: "babyDragon.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    beardedDragon: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "beardedDragon_2D",
        meshPath: "/2DAssets/pets/beardedDragon/",
        meshFile: "beardedDragon_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "beardedDragon_gltf",
        meshPath: "/3DAssets/pets/beardedDragon/",
        meshFile: "beardedDragon.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    bird1: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "bird1_2D",
        meshPath: "/2DAssets/pets/bird1/",
        meshFile: "bird1_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "bird1_gltf",
        meshPath: "/3DAssets/pets/bird1/",
        meshFile: "bird1.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    bird2: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "bird2_2D",
        meshPath: "/2DAssets/pets/bird2/",
        meshFile: "bird2_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "bird2_gltf",
        meshPath: "/3DAssets/pets/bird2/",
        meshFile: "bird2.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    boxer: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "boxer_2D",
        meshPath: "/2DAssets/pets/boxer/",
        meshFile: "boxer_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "boxer_gltf",
        meshPath: "/3DAssets/pets/boxer/",
        meshFile: "boxer.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    brain: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "brain_2D",
        meshPath: "/2DAssets/pets/brain/",
        meshFile: "brain_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "brain_gltf",
        meshPath: "/3DAssets/pets/brain/",
        meshFile: "brain.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    buddyHamster: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "buddyHamster_2D",
        meshPath: "/2DAssets/pets/buddyHamster/",
        meshFile: "buddyHamster_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "buddyHamster_gltf",
        meshPath: "/3DAssets/pets/buddyHamster/",
        meshFile: "buddyHamster.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    cat1: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "cat1_2D",
        meshPath: "/2DAssets/pets/cat1/",
        meshFile: "cat1_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "cat1_gltf",
        meshPath: "/3DAssets/pets/cat1/",
        meshFile: "cat1.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    cat2: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "cat2_2D",
        meshPath: "/2DAssets/pets/cat2/",
        meshFile: "cat2_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "cat2_gltf",
        meshPath: "/3DAssets/pets/cat2/",
        meshFile: "cat2.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    dodoBird: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "dodoBird_2D",
        meshPath: "/2DAssets/pets/dodoBird/",
        meshFile: "dodoBird_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "dodoBird_gltf",
        meshPath: "/3DAssets/pets/dodoBird/",
        meshFile: "dodoBird.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    happyHamster: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "happyHamster_2D",
        meshPath: "/2DAssets/pets/happyHamster/",
        meshFile: "happyHamster_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "happyHamster_gltf",
        meshPath: "/3DAssets/pets/happyHamster/",
        meshFile: "happyHamster.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    mechanicalGrasshopper: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "mechanicalGrasshopper_2D",
        meshPath: "/2DAssets/pets/mechanicalGrasshopper/",
        meshFile: "mechanicalGrasshopper_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "mechanicalGrasshopper_gltf",
        meshPath: "/3DAssets/pets/mechanicalGrasshopper/",
        meshFile: "mechanicalGrasshopper.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    panda1: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "panda1_2D",
        meshPath: "/2DAssets/pets/panda1/",
        meshFile: "panda1_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "panda1_gltf",
        meshPath: "/3DAssets/pets/panda1/",
        meshFile: "panda1.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    panda2: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "panda2_2D",
        meshPath: "/2DAssets/pets/panda2/",
        meshFile: "panda2_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "panda2_gltf",
        meshPath: "/3DAssets/pets/panda2/",
        meshFile: "panda2.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    petRock: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "petRock_2D",
        meshPath: "/2DAssets/pets/petRock/",
        meshFile: "petRock_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "petRock_gltf",
        meshPath: "/3DAssets/pets/petRock/",
        meshFile: "petRock2.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    pig: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "pig_2D",
        meshPath: "/2DAssets/pets/pig/",
        meshFile: "pig_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "pig_gltf",
        meshPath: "/3DAssets/pets/pig/",
        meshFile: "pig.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    redFox1: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "redFox1_2D",
        meshPath: "/2DAssets/pets/redFox1/",
        meshFile: "redFox1_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "redFox1_gltf",
        meshPath: "/3DAssets/pets/redFox1/",
        meshFile: "redFox1.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    redFox2: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "redFox2_2D",
        meshPath: "/2DAssets/pets/redFox2/",
        meshFile: "redFox2_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "redFox2_gltf",
        meshPath: "/3DAssets/pets/redFox2/",
        meshFile: "redFox2.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    roboDog: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "roboDog_2D",
        meshPath: "/2DAssets/pets/roboDog/",
        meshFile: "roboDog_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "roboDog_gltf",
        meshPath: "/3DAssets/pets/roboDog/",
        meshFile: "roboDog.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    skeletonTRex: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "skeletonTRex_2D",
        meshPath: "/2DAssets/pets/skeletonTRex/",
        meshFile: "skeletonTRex_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "skeletonTRex_gltf",
        meshPath: "/3DAssets/pets/skeletonTRex/",
        meshFile: "skeletonTRex.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    snail: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "snail_2D",
        meshPath: "/2DAssets/pets/snail/",
        meshFile: "snail_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "snail_gltf",
        meshPath: "/3DAssets/pets/snail/",
        meshFile: "snail.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    spinosaurus: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "spinosaurus_2D",
        meshPath: "/2DAssets/pets/spinosaurus/",
        meshFile: "spinosaurus_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "spinosaurus_gltf",
        meshPath: "/3DAssets/pets/spinosaurus/",
        meshFile: "spinosaurus.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
    TRex: {
      defaultMeshPlacement: "forehead",
      planeMesh: {
        meshLabel: "TRex_2D",
        meshPath: "/2DAssets/pets/TRex/",
        meshFile: "TRex_512x512.png",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
      mesh: {
        meshType: "gltf",
        meshLabel: "TRex_gltf",
        meshPath: "/3DAssets/pets/TRex/",
        meshFile: "TRex2.gltf",
        initScale: [1, 1, 1],
        initRotation: [0, 0, 0],
      },
    },
  },
};

export const hideBackgroundEffectImagesMap: {
  [hideBackgroundEffectType in HideBackgroundEffectTypes]?: string;
} = {
  beach: "/videoBackgrounds/beach_640x427.jpg",
  brickWall: "/videoBackgrounds/brickWall_640x427.jpg",
  butterflies: "/videoBackgrounds/butterflies_640x360.jpg",
  cafe: "/videoBackgrounds/cafe_427x640.jpg",
  chalkBoard: "/videoBackgrounds/chalkBoard_640x427.jpg",
  citySkyline: "/videoBackgrounds/citySkyline_640x331.jpg",
  cliffPalace:
    "/videoBackgrounds/cliffPalaceMesaVerdeNationalParkByAnselAdams_608x750.jpg",
  eveningMcDonaldLake:
    "/videoBackgrounds/eveningMcDonaldLakeGlacierNationalParkMontanaByAnselAdams_750x569.jpg",
  forest: "/videoBackgrounds/forest_640x427.jpg",
  halfDomeAppleOrchard:
    "/videoBackgrounds/halfDomeAppleOrchardYosemiteCaliforniaByAnselAdams_750x575.jpg",
  lake: "/videoBackgrounds/lake_640x457.jpg",
  library: "/videoBackgrounds/library_640x427.jpg",
  milkyWay: "/videoBackgrounds/milkyWay_640x349.jpg",
  mountains: "/videoBackgrounds/mountains_640x425.jpg",
  ocean: "/videoBackgrounds/ocean_640x427.jpg",
  oldFaithfulGeyser:
    "/videoBackgrounds/oldFaithfulGeyserYellowstoneNationalParkWyomingByAnselAdams_532x750.jpg",
  railroad: "/videoBackgrounds/railroad_640x414.jpg",
  rollingHills: "/videoBackgrounds/rollingHills_640x417.jpg",
  seaSideHouses: "/videoBackgrounds/seaSideHouses_640x390.jpg",
  snowCoveredMoutains: "/videoBackgrounds/snowCoveredMoutains_640x360.jpg",
  sunflowers: "/videoBackgrounds/sunflowers_640x427.jpg",
  sunset: "/videoBackgrounds/sunset_640x427.jpg",
  trees: "/videoBackgrounds/trees_640x426.jpg",
  windingRoad: "/videoBackgrounds/windingRoad_640x427.jpg",
};

export default assetMeshes;
