import { MeshesData, MeshJSON } from "../../../universal/babylonTypeContant";
import { HideBackgroundEffectTypes } from "../../../universal/effectsTypeConstant";

const nginxAssetServerBaseUrl = process.env.NGINX_ASSET_SERVER_BASE_URL;

export const baseMaskData: {
  "2Durl": string;
  "3Durl": string;
  size: number;
  data: MeshJSON | undefined;
} = {
  "2Durl":
    nginxAssetServerBaseUrl + "2DAssets/masks/baseMask/baseMask_512x512.png",
  "3Durl": nginxAssetServerBaseUrl + "3DAssets/masks/baseMask/baseMask.json",
  size: 512,
  data: undefined,
};

const assetMeshes: MeshesData = {
  mustaches: {
    disguiseMustache: {
      defaultMeshPlacement: "nose",
      meshType: "gltf",
      meshLabel: "disguiseMustache_gltf",
      meshPath:
        nginxAssetServerBaseUrl + "3DAssets/mustaches/disguiseMustache/",
      meshFile: "disguiseMustache.gltf",
      initScale: [1.75, 1.75, 1.75],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 0 },
    },
    fullMustache: {
      defaultMeshPlacement: "nose",
      meshType: "gltf",
      meshLabel: "fullMustache_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/mustaches/fullMustache/",
      meshFile: "fullMustache.gltf",
      initScale: [1.5, 1.5, 1.5],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/mustaches/fullMustache.mp3",
      transforms: { offsetX: 0, offsetY: -5 },
    },
    mustache1: {
      defaultMeshPlacement: "nose",
      meshType: "gltf",
      meshLabel: "mustache1_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/mustaches/mustache1/",
      meshFile: "mustache1.gltf",
      initScale: [0.4375, 0.4375, 0.4375],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/mustaches/mustache1.mp3",
      transforms: { offsetX: 0, offsetY: -3.5 },
    },
    mustache2: {
      defaultMeshPlacement: "nose",
      meshType: "gltf",
      meshLabel: "mustache2_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/mustaches/mustache2/",
      meshFile: "mustache2.gltf",
      initScale: [0.4375, 0.4375, 0.4375],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/mustaches/mustache2.mp3",
      transforms: { offsetX: 0, offsetY: -3.5 },
    },
    mustache3: {
      defaultMeshPlacement: "nose",
      meshType: "gltf",
      meshLabel: "mustache3_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/mustaches/mustache3/",
      meshFile: "mustache3.gltf",
      initScale: [0.4375, 0.4375, 0.4375],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/mustaches/mustache3.mp3",
      transforms: { offsetX: 0, offsetY: -3.5 },
    },
    mustache4: {
      defaultMeshPlacement: "nose",
      meshType: "gltf",
      meshLabel: "mustache4_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/mustaches/mustache4/",
      meshFile: "mustache4.gltf",
      initScale: [0.4375, 0.4375, 0.4375],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: -2 },
    },
    nicodemusMustache: {
      defaultMeshPlacement: "nose",
      meshType: "gltf",
      meshLabel: "nicodemusMustache_gltf",
      meshPath:
        nginxAssetServerBaseUrl + "3DAssets/mustaches/nicodemusMustache/",
      meshFile: "nicodemusMustache.gltf",
      initScale: [1.75, 1.75, 1.75],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: -3 },
    },
    pencilMustache: {
      defaultMeshPlacement: "nose",
      meshType: "gltf",
      meshLabel: "pencilMustache_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/mustaches/pencilMustache/",
      meshFile: "pencilMustache.gltf",
      initScale: [1, 1, 1],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/mustaches/pencilMustache.mp3",
      transforms: { offsetX: 0, offsetY: -2.5 },
    },
    spongebobMustache: {
      defaultMeshPlacement: "nose",
      meshType: "gltf",
      meshLabel: "spongebobMustache_gltf",
      meshPath:
        nginxAssetServerBaseUrl + "3DAssets/mustaches/spongebobMustache/",
      meshFile: "spongebobMustache.gltf",
      initScale: [1.5, 1.5, 1.5],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: -2.5 },
    },
    tinyMustache: {
      defaultMeshPlacement: "nose",
      meshType: "gltf",
      meshLabel: "tinyMustache_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/mustaches/tinyMustache/",
      meshFile: "tinyMustache.gltf",
      initScale: [1, 1, 1],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: -2 },
    },
    wingedMustache: {
      defaultMeshPlacement: "nose",
      meshType: "gltf",
      meshLabel: "wingedMustache_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/mustaches/wingedMustache/",
      meshFile: "wingedMustache.gltf",
      initScale: [1, 1, 1],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: -3 },
    },
  },
  beards: {
    chinBeard: {
      defaultMeshPlacement: "chin",
      meshType: "gltf",
      meshLabel: "chinBeard_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/beards/chinBeard/",
      meshFile: "chinBeard.gltf",
      initScale: [0.625, 0.625, 0.625],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 6 },
    },
    classicalCurlyBeard: {
      defaultMeshPlacement: "nose",
      meshType: "gltf",
      meshLabel: "classicalCurlyBeard_gltf",
      meshPath:
        nginxAssetServerBaseUrl + "3DAssets/beards/classicalCurlyBeard/",
      meshFile: "classicalCurlyBeard.gltf",
      initScale: [1.875, 1.875, 1.875],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: -28 },
    },
    fullBeard: {
      defaultMeshPlacement: "nose",
      meshType: "gltf",
      meshLabel: "fullBeard_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/beards/fullBeard/",
      meshFile: "fullBeard.gltf",
      initScale: [3, 2.5, 2.5],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: -17 },
    },
  },
  masks: {
    alienMask: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "alienMask_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/alienMask/",
      meshFile: "alienMask.gltf",
      initScale: [4.25, 4, 4],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/masks/alienMask.mp3",
      transforms: { offsetX: 0, offsetY: -1 },
    },
    baseMask: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "baseMask_gltf",
      meshPath: nginxAssetServerBaseUrl + "",
      meshFile: "",
      initScale: [0, 0, 0],
      initRotation: [0, 0, 0],
      soundEffectPath: nginxAssetServerBaseUrl + "audioAssets/masks/.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    clownMask: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "clownMask_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/clownMask/",
      meshFile: "clownMask.gltf",
      initScale: [3.75, 3.75, 3.75],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/masks/clownMask.mp3",
      transforms: { offsetX: 0, offsetY: -0.5 },
    },
    creatureMask: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "creatureMask_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/creatureMask/",
      meshFile: "creatureMask.gltf",
      initScale: [3.75, 3.75, 3.75],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/masks/creatureMask.mp3",
      transforms: { offsetX: 0, offsetY: -1.5 },
    },
    cyberMask: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "cyberMask_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/cyberMask/",
      meshFile: "cyberMask.gltf",
      initScale: [4.25, 4, 4],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/masks/cyberMask.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    darkKnightMask: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "darkKnightMask_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/darkKnightMask/",
      meshFile: "darkKnightMask.gltf",
      initScale: [4.5, 4.25, 4.25],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/masks/darkKnightMask.mp3",
      transforms: { offsetX: 0, offsetY: -1 },
    },
    demonMask: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "demonMask_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/demonMask/",
      meshFile: "demonMask.gltf",
      initScale: [3.75, 3.75, 3.75],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/masks/demonMask.mp3",
      transforms: { offsetX: 0, offsetY: -0.5 },
    },
    gasMask1: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "gasMask1_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/gasMask1/",
      meshFile: "gasMask1.gltf",
      initScale: [3.25, 3.25, 3.25],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/masks/gasMask1.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    gasMask2: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "gasMask2_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/gasMask2/",
      meshFile: "gasMask2.gltf",
      initScale: [3.25, 3.25, 3.25],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/masks/gasMask2.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    gasMask3: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "gasMask3_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/gasMask3/",
      meshFile: "gasMask3.gltf",
      initScale: [3.25, 3.25, 3.25],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/masks/gasMask3.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    gasMask4: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "gasMask4_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/gasMask4/",
      meshFile: "gasMask4.gltf",
      initScale: [3.25, 3.25, 3.25],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/masks/gasMask4.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    masqueradeMask: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "masqueradeMask_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/masqueradeMask/",
      meshFile: "masqueradeMask.gltf",
      initScale: [5, 5, 5],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/masks/masqueradeMask.mp3",
      transforms: { offsetX: 0, offsetY: -0.5 },
    },
    metalManMask: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "metalManMask_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/metalManMask/",
      meshFile: "metalManMask.gltf",
      initScale: [4, 4, 4],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/masks/metalManMask.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    oniMask: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "oniMask_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/oniMask/",
      meshFile: "oniMask.gltf",
      initScale: [3.5, 3.25, 3.25],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/masks/oniMask.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    plagueDoctorMask: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "plagueDoctorMask_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/plagueDoctorMask/",
      meshFile: "plagueDoctorMask.gltf",
      initScale: [4.25, 4, 4],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/masks/plagueDoctorMask.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    sixEyesMask: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "sixEyesMask_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/sixEyesMask/",
      meshFile: "sixEyesMask.gltf",
      initScale: [3.25, 3.25, 3.25],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/masks/sixEyesMask.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    tenguMask: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "tenguMask_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/tenguMask/",
      meshFile: "tenguMask.gltf",
      initScale: [3.25, 2.75, 2.75],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 0 },
    },
    threeFaceMask: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "threeFaceMask_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/threeFaceMask/",
      meshFile: "threeFaceMask.gltf",
      initScale: [3, 3, 3],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/masks/threeFaceMask.mp3",
      transforms: { offsetX: 0, offsetY: -0.5 },
    },
    weldingMask: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "weldingMask_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/weldingMask/",
      meshFile: "weldingMask.gltf",
      initScale: [3.25, 3.25, 3.25],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/masks/weldingMask.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    woodlandMask: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "woodlandMask_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/woodlandMask/",
      meshFile: "woodlandMask.gltf",
      initScale: [3.75, 3.5, 3.5],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/masks/woodlandMask.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    woodPaintedMask: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "woodPaintedMask_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/woodPaintedMask/",
      meshFile: "woodPaintedMask.gltf",
      initScale: [4, 4, 4],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/masks/woodPaintedMask.mp3",
      transforms: { offsetX: 0, offsetY: -0.5 },
    },
    zombieMask: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "zombieMask_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/masks/zombieMask/",
      meshFile: "zombieMask.gltf",
      initScale: [4.5, 4.25, 4.25],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/masks/zombieMask.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
  },
  glasses: {
    defaultGlasses: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "defaultGlasses_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/glasses/defaultGlasses/",
      meshFile: "defaultGlasses.gltf",
      initScale: [1.25, 1.25, 1.25],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 1.5 },
    },
    aviatorGoggles: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "aviatorGoggles_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/glasses/aviatorGoggles/",
      meshFile: "aviatorGoggles.gltf",
      initScale: [1.75, 1.75, 1.75],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/glasses/aviatorGoggles.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    bloodyGlasses: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "bloodyGlasses_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/glasses/bloodyGlasses/",
      meshFile: "bloodyGlasses.gltf",
      initScale: [1.75, 1.75, 1.75],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/glasses/bloodyGlasses.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    eyeProtectionGlasses: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "eyeProtectionGlasses_gltf",
      meshPath:
        nginxAssetServerBaseUrl + "3DAssets/glasses/eyeProtectionGlasses/",
      meshFile: "eyeProtectionGlasses.gltf",
      initScale: [1.625, 1.625, 1.625],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl +
        "audioAssets/glasses/eyeProtectionGlasses.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    glasses1: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "glasses1_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/glasses/glasses1/",
      meshFile: "glasses1.gltf",
      initScale: [1.5, 1.5, 1.5],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 0 },
    },
    glasses2: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "glasses2_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/glasses/glasses2/",
      meshFile: "glasses2.gltf",
      initScale: [1.375, 1.375, 1.375],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 0 },
    },
    glasses3: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "glasses3_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/glasses/glasses3/",
      meshFile: "glasses3.gltf",
      initScale: [1.625, 1.625, 0.625],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 0 },
    },
    glasses4: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "glasses4_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/glasses/glasses4/",
      meshFile: "glasses4.gltf",
      initScale: [1.5, 1.5, 1.5],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 0 },
    },
    glasses5: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "glasses5_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/glasses/glasses5/",
      meshFile: "glasses5.gltf",
      initScale: [1.5, 1.5, 1.5],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 0 },
    },
    glasses6: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "glasses6_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/glasses/glasses6/",
      meshFile: "glasses6.gltf",
      initScale: [1.5, 1.5, 1.5],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 0 },
    },
    memeGlasses: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "memeGlasses_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/glasses/memeGlasses/",
      meshFile: "memeGlasses.gltf",
      initScale: [1.75, 1.75, 1.75],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/glasses/memeGlasses.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    militaryTacticalGlasses: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "militaryTacticalGlasses_gltf",
      meshPath:
        nginxAssetServerBaseUrl + "3DAssets/glasses/militaryTacticalGlasses/",
      meshFile: "militaryTacticalGlasses.gltf",
      initScale: [2, 2, 2],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl +
        "audioAssets/glasses/militaryTacticalGlasses.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    steampunkGlasses: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "steampunkGlasses_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/glasses/steampunkGlasses/",
      meshFile: "steampunkGlasses.gltf",
      initScale: [1.75, 1.75, 1.75],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/glasses/steampunkGlasses.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    threeDGlasses: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "threeDGlasses_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/glasses/threeDGlasses/",
      meshFile: "threeDGlasses.gltf",
      initScale: [1.625, 1.625, 1.625],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 0 },
    },
    toyGlasses: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "toyGlasses_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/glasses/toyGlasses/",
      meshFile: "toyGlasses.gltf",
      initScale: [1.75, 1.75, 1.75],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/glasses/toyGlasses.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    shades: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "shades_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/glasses/shades/",
      meshFile: "shades.gltf",
      initScale: [1.625, 1.625, 1.625],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 3.5 },
    },
    VRGlasses: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "VRGlasses_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/glasses/VRGlasses/",
      meshFile: "VRGlasses.gltf",
      initScale: [2, 2, 2],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 0 },
    },
  },
  hats: {
    AsianConicalHat: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "AsianConicalHat_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/hats/AsianConicalHat/",
      meshFile: "AsianConicalHat.gltf",
      initScale: [1.25, 1.25, 1.25],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 0 },
    },
    aviatorHelmet: {
      defaultMeshPlacement: "eyesCenter",
      meshType: "gltf",
      meshLabel: "aviatorHelmet_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/hats/aviatorHelmet/",
      meshFile: "aviatorHelmet.gltf",
      initScale: [1.625, 1.625, 1.625],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/hats/aviatorHelmet.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    bicornHat: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "bicornHat_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/hats/bicornHat/",
      meshFile: "bicornHat.gltf",
      initScale: [2, 2, 2],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 0 },
    },
    bicycleHelmet: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "bicycleHelmet_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/hats/bicycleHelmet/",
      meshFile: "bicycleHelmet.gltf",
      initScale: [2, 2, 2],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/hats/bicycleHelmet.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    captainsHat: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "captainsHat_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/hats/captainsHat/",
      meshFile: "captainsHat.gltf",
      initScale: [2.5, 2.5, 2.5],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/hats/captainsHat.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    chefHat: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "chefHat_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/hats/chefHat/",
      meshFile: "chefHat.gltf",
      initScale: [1.675, 1.675, 1.675],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 0 },
    },
    chickenHat: {
      defaultMeshPlacement: "nose",
      meshType: "gltf",
      meshLabel: "chickenHat_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/hats/chickenHat/",
      meshFile: "chickenHat.gltf",
      initScale: [2.5, 2.5, 2.5],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/hats/chickenHat.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    deadManHat: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "deadManHat_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/hats/deadManHat/",
      meshFile: "deadManHat.gltf",
      initScale: [2.25, 2.25, 2.25],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/hats/deadManHat.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    dogEars: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "dogEars_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/hats/dogEars/",
      meshFile: "dogEars.gltf",
      initScale: [1.25, 1.25, 1.25],
      initRotation: [0, 0, 0],
      soundEffectPath: nginxAssetServerBaseUrl + "audioAssets/hats/dogEars.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    flatCap: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "flatCap_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/hats/flatCap/",
      meshFile: "flatCap.gltf",
      initScale: [2, 2, 2],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 0 },
    },
    hardHat: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "hardHat_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/hats/hardHat/",
      meshFile: "hardHat.gltf",
      initScale: [2.5, 2.5, 2.5],
      initRotation: [0, 0, 0],
      soundEffectPath: nginxAssetServerBaseUrl + "audioAssets/hats/hardHat.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    hopliteHelmet: {
      defaultMeshPlacement: "nose",
      meshType: "gltf",
      meshLabel: "hopliteHelmet_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/hats/hopliteHelmet/",
      meshFile: "hopliteHelmet.gltf",
      initScale: [4.75, 4.75, 4.75],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/hats/hopliteHelmet.mp3",
      transforms: { offsetX: 0, offsetY: 6 },
    },
    militaryHat: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "militaryHat_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/hats/militaryHat/",
      meshFile: "militaryHat.gltf",
      initScale: [2.25, 2.25, 2.25],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 0 },
    },
    rabbitEars: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "rabbitEars_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/hats/rabbitEars/",
      meshFile: "rabbitEars.gltf",
      initScale: [1.5, 1.5, 1.5],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/hats/rabbitEars.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    santaHat: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "santaHat_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/hats/santaHat/",
      meshFile: "santaHat.gltf",
      initScale: [2.375, 2.375, 2.375],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/hats/santaHat.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    seamanHat: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "seamanHat_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/hats/seamanHat/",
      meshFile: "seamanHat.gltf",
      initScale: [1.875, 1.875, 1.875],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/hats/seamanHat.mp3",
      transforms: { offsetX: 0, offsetY: 0 },
    },
    stylishHat: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "stylishHat_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/hats/stylishHat/",
      meshFile: "stylishHat.gltf",
      initScale: [1.5, 1.5, 1.5],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 0 },
    },
    ushankaHat: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "ushankaHat_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/hats/ushankaHat/",
      meshFile: "ushankaHat.gltf",
      initScale: [1.375, 1.375, 1.375],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 0 },
    },
    vikingHelmet: {
      defaultMeshPlacement: "nose",
      meshType: "gltf",
      meshLabel: "vikingHelmet_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/hats/vikingHelmet/",
      meshFile: "vikingHelmet.gltf",
      initScale: [2.25, 2.25, 2.25],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/hats/vikingHelmet.mp3",
      transforms: { offsetX: 0, offsetY: 2 },
    },
  },
  pets: {
    angryHamster: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "angryHamster_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/angryHamster/",
      meshFile: "angryHamster.gltf",
      initScale: [1.25, 1.25, 1.25],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 8 },
    },
    axolotl: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "axolotl_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/axolotl/",
      meshFile: "axolotl.gltf",
      initScale: [1.25, 1.25, 1.25],
      initRotation: [0, 0, 0],
      soundEffectPath: nginxAssetServerBaseUrl + "audioAssets/pets/axolotl.mp3",
      transforms: { offsetX: 0, offsetY: 20 },
    },
    babyDragon: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "babyDragon_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/babyDragon/",
      meshFile: "babyDragon.gltf",
      initScale: [1.25, 1.25, 1.25],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/pets/babyDragon.mp3",
      transforms: { offsetX: 0, offsetY: 8 },
    },
    beardedDragon: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "beardedDragon_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/beardedDragon/",
      meshFile: "beardedDragon.gltf",
      initScale: [1.5, 1.5, 1.5],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 8 },
    },
    bird1: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "bird1_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/bird1/",
      meshFile: "bird1.gltf",
      initScale: [1.25, 1.25, 1.25],
      initRotation: [0, 0, 0],
      soundEffectPath: nginxAssetServerBaseUrl + "audioAssets/pets/bird1.mp3",
      transforms: { offsetX: 0, offsetY: 8 },
    },
    bird2: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "bird2_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/bird2/",
      meshFile: "bird2.gltf",
      initScale: [1.5, 1.5, 1.5],
      initRotation: [0, 0, 0],
      soundEffectPath: nginxAssetServerBaseUrl + "audioAssets/pets/bird2.mp3",
      transforms: { offsetX: 0, offsetY: 12 },
    },
    boxer: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "boxer_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/boxer/",
      meshFile: "boxer.gltf",
      initScale: [1.5, 1.5, 1.5],
      initRotation: [0, 0, 0],
      soundEffectPath: nginxAssetServerBaseUrl + "audioAssets/pets/boxer.mp3",
      transforms: { offsetX: 0, offsetY: 4 },
    },
    brain: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "brain_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/brain/",
      meshFile: "brain.gltf",
      initScale: [1.5, 1.5, 1.5],
      initRotation: [0, 0, 0],
      soundEffectPath: nginxAssetServerBaseUrl + "audioAssets/pets/brain.mp3",
      transforms: { offsetX: 0, offsetY: 8 },
    },
    buddyHamster: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "buddyHamster_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/buddyHamster/",
      meshFile: "buddyHamster.gltf",
      initScale: [1, 1, 1],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 16 },
    },
    cat1: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "cat1_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/cat1/",
      meshFile: "cat1.gltf",
      initScale: [1, 1, 1],
      initRotation: [0, 0, 0],
      soundEffectPath: nginxAssetServerBaseUrl + "audioAssets/pets/cat1.mp3",
      transforms: { offsetX: 0, offsetY: 28 },
    },
    cat2: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "cat2_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/cat2/",
      meshFile: "cat2.gltf",
      initScale: [1, 1, 1],
      initRotation: [0, 0, 0],
      soundEffectPath: nginxAssetServerBaseUrl + "audioAssets/pets/cat2.mp3",
      transforms: { offsetX: 0, offsetY: 16 },
    },
    dodoBird: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "dodoBird_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/dodoBird/",
      meshFile: "dodoBird.gltf",
      initScale: [1.25, 1.25, 1.25],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 20 },
    },
    happyHamster: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "happyHamster_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/happyHamster/",
      meshFile: "happyHamster.gltf",
      initScale: [0.75, 0.75, 0.75],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 16 },
    },
    mechanicalGrasshopper: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "mechanicalGrasshopper_gltf",
      meshPath:
        nginxAssetServerBaseUrl + "3DAssets/pets/mechanicalGrasshopper/",
      meshFile: "mechanicalGrasshopper.gltf",
      initScale: [1.5, 1.5, 1.5],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/pets/mechanicalGrasshopper.mp3",
      transforms: { offsetX: 0, offsetY: 16 },
    },
    panda1: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "panda1_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/panda1/",
      meshFile: "panda1.gltf",
      initScale: [1, 1, 1],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 24 },
    },
    panda2: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "panda2_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/panda2/",
      meshFile: "panda2.gltf",
      initScale: [1.25, 1.25, 1.25],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 24 },
    },
    petRock: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "petRock_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/petRock/",
      meshFile: "petRock.gltf",
      initScale: [0.5, 0.5, 0.5],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 12 },
    },
    pig: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "pig_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/pig/",
      meshFile: "pig.gltf",
      initScale: [1.25, 1.25, 1.25],
      initRotation: [0, 0, 0],
      soundEffectPath: nginxAssetServerBaseUrl + "audioAssets/pets/pig.mp3",
      transforms: { offsetX: 0, offsetY: 8 },
    },
    redFox1: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "redFox1_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/redFox1/",
      meshFile: "redFox1.gltf",
      initScale: [1.25, 1.25, 1.25],
      initRotation: [0, 0, 0],
      soundEffectPath: nginxAssetServerBaseUrl + "audioAssets/pets/redFox1.mp3",
      transforms: { offsetX: 0, offsetY: 8 },
    },
    redFox2: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "redFox2_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/redFox2/",
      meshFile: "redFox2.gltf",
      initScale: [1.625, 1.625, 1.625],
      initRotation: [0, 0, 0],
      soundEffectPath: nginxAssetServerBaseUrl + "audioAssets/pets/redFox2.mp3",
      transforms: { offsetX: 0, offsetY: 8 },
    },
    roboDog: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "roboDog_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/roboDog/",
      meshFile: "roboDog.gltf",
      initScale: [1.25, 1.25, 1.25],
      initRotation: [0, 0, 0],
      soundEffectPath: nginxAssetServerBaseUrl + "audioAssets/pets/roboDog.mp3",
      transforms: { offsetX: 0, offsetY: 16 },
    },
    skeletonTRex: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "skeletonTRex_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/skeletonTRex/",
      meshFile: "skeletonTRex.gltf",
      initScale: [1.5, 1.5, 1.5],
      initRotation: [0, 0, 0],
      soundEffectPath: undefined,
      transforms: { offsetX: 0, offsetY: 8 },
    },
    snail: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "snail_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/snail/",
      meshFile: "snail.gltf",
      initScale: [1, 1, 1],
      initRotation: [0, 0, 0],
      soundEffectPath: nginxAssetServerBaseUrl + "audioAssets/pets/snail.mp3",
      transforms: { offsetX: 0, offsetY: 8 },
    },
    spinosaurus: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "spinosaurus_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/spinosaurus/",
      meshFile: "spinosaurus.gltf",
      initScale: [1.625, 1.625, 1.625],
      initRotation: [0, 0, 0],
      soundEffectPath:
        nginxAssetServerBaseUrl + "audioAssets/pets/spinosaurus.mp3",
      transforms: { offsetX: 0, offsetY: 8 },
    },
    TRex: {
      defaultMeshPlacement: "forehead",
      meshType: "gltf",
      meshLabel: "TRex_gltf",
      meshPath: nginxAssetServerBaseUrl + "3DAssets/pets/TRex/",
      meshFile: "TRex.gltf",
      initScale: [0.004, 0.004, 0.004],
      initRotation: [0, 0, 0],
      soundEffectPath: nginxAssetServerBaseUrl + "audioAssets/pets/TRex.mp3",
      transforms: { offsetX: 0, offsetY: 8 },
    },
  },
};

export const hideBackgroundEffectImagesMap: {
  [hideBackgroundEffectType in HideBackgroundEffectTypes]?: string;
} = {
  beach: nginxAssetServerBaseUrl + "videoBackgrounds/beach_640x427.jpg",
  brickWall: nginxAssetServerBaseUrl + "videoBackgrounds/brickWall_640x427.jpg",
  butterflies:
    nginxAssetServerBaseUrl + "videoBackgrounds/butterflies_640x360.jpg",
  cafe: nginxAssetServerBaseUrl + "videoBackgrounds/cafe_427x640.jpg",
  chalkBoard:
    nginxAssetServerBaseUrl + "videoBackgrounds/chalkBoard_640x427.jpg",
  citySkyline:
    nginxAssetServerBaseUrl + "videoBackgrounds/citySkyline_640x331.jpg",
  cliffPalace:
    nginxAssetServerBaseUrl +
    "videoBackgrounds/cliffPalaceMesaVerdeNationalParkByAnselAdams_608x750.jpg",
  eveningMcDonaldLake:
    nginxAssetServerBaseUrl +
    "videoBackgrounds/eveningMcDonaldLakeGlacierNationalParkMontanaByAnselAdams_750x569.jpg",
  forest: nginxAssetServerBaseUrl + "videoBackgrounds/forest_640x427.jpg",
  halfDomeAppleOrchard:
    nginxAssetServerBaseUrl +
    "videoBackgrounds/halfDomeAppleOrchardYosemiteCaliforniaByAnselAdams_750x575.jpg",
  lake: nginxAssetServerBaseUrl + "videoBackgrounds/lake_640x457.jpg",
  library: nginxAssetServerBaseUrl + "videoBackgrounds/library_640x427.jpg",
  milkyWay: nginxAssetServerBaseUrl + "videoBackgrounds/milkyWay_640x349.jpg",
  mountains: nginxAssetServerBaseUrl + "videoBackgrounds/mountains_640x425.jpg",
  ocean: nginxAssetServerBaseUrl + "videoBackgrounds/ocean_640x427.jpg",
  oldFaithfulGeyser:
    nginxAssetServerBaseUrl +
    "videoBackgrounds/oldFaithfulGeyserYellowstoneNationalParkWyomingByAnselAdams_532x750.jpg",
  railroad: nginxAssetServerBaseUrl + "videoBackgrounds/railroad_640x414.jpg",
  rollingHills:
    nginxAssetServerBaseUrl + "videoBackgrounds/rollingHills_640x417.jpg",
  seaSideHouses:
    nginxAssetServerBaseUrl + "videoBackgrounds/seaSideHouses_640x390.jpg",
  snowCoveredMoutains:
    nginxAssetServerBaseUrl +
    "videoBackgrounds/snowCoveredMoutains_640x360.jpg",
  sunflowers:
    nginxAssetServerBaseUrl + "videoBackgrounds/sunflowers_640x427.jpg",
  sunset: nginxAssetServerBaseUrl + "videoBackgrounds/sunset_640x427.jpg",
  trees: nginxAssetServerBaseUrl + "videoBackgrounds/trees_640x426.jpg",
  windingRoad:
    nginxAssetServerBaseUrl + "videoBackgrounds/windingRoad_640x427.jpg",
};

export default assetMeshes;
